### ISSUE TITLE
Feature: 2019 Roadmap

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#104]
It would be great to have a well defined vision and roadmap for 2019.

**Describe the solution you'd like**
Ideally, this would look similar to what the [IPFS Community WG](https://github.com/ipfs/community/blob/master/ROADMAP.md) has and what [IPLD has](https://github.com/ipld/roadmap).

**Comment by terichadbourne** [comment]
Dropping in some links to roadmapping resources I'd like to review: 
- Molly's roadmapping [video tutorial(https://drive.google.com/file/d/1STMSvtwmUIxEFrzwCJaLBmtqZazrugTJ/view) and [slides](https://docs.google.com/presentation/d/1sX0x1znGN5HJpd3vB7HmDen_X72HkTPRxIv5vUlNGe0/edit#slide=id.g4582a137f5_0_296)
- [Roadmap How-To & Format Doc](https://github.com/ipfs/team-mgmt/blob/master/ROADMAP_HOW_TO.md)
- [IPFS Team Coordination Toolkit](https://github.com/ipfs/pm/blob/master/TEAM_COORDINATION_TOOLKIT.md) 
- [On writing product roadmaps](https://goberoi.com/on-writing-product-roadmaps-a4d72f96326c)
- [Filecoin Project Roadmap](https://docs.google.com/document/d/1cgss-rifFO2iSJgnMmOsD_tPal40MUp1m7crTFQuVYQ/edit)
- [Roadmap Examples and Templates](https://docs.google.com/document/d/1LFRr-Y618B47PB2e3BKBaK1FGaGm8Go49UQQVSPBhho/edit#)

**Comment by terichadbourne** [comment]
At @mikeal's suggestion, I've created a document where we can engage in a messaging exercise to start us thinking about the audience and goals of ProtoSchool. Please weigh in at: 

https://docs.google.com/document/d/1XVd_ZVmjVOLYoGHACX3x5zJEuFP-6aEm-AzZZbtUkMI/edit?usp=sharing

**Comment by terichadbourne** [comment]
I've dropped issues in major project repos asking how PL can best meet the needs of each team.  https://github.com/search?q=%22how+can+protoschool+best%22&type=Issues

**Comment by terichadbourne** [comment]
Initial roadmap and Q2 OKRs are in a PR in a new repo here: https://github.com/ProtoSchool/roadmap/pulls

**Comment by terichadbourne** [comment]
A video of me presenting the proposed roadmap to the IPFS Community Working Group is available here: https://youtu.be/mGClQ2vPMu0?t=1159
