### ISSUE TITLE
Improve responsive design, esp nav bar

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#108]
The navigation bar currently gets cut off on narrower screen widths, so we need a hamburger menu or the like to make it accessible on mobile. 

Other site content works better responsively, but we should do a quick review of it when fixing the nav to see what else needs improvement.

**Comment by terichadbourne** [comment]
Currently on a phone or other narrow screen, the nav bar extends further right than the viewport, while the rest of the content stays in the viewport. 

![image](https://user-images.githubusercontent.com/19171465/50597828-bceba380-0e76-11e9-8559-80da64b2d014.png)

If you scroll right to see it, the background is missing, so if you visit a page and its title gets highlighted in white, it's invisible. For example, while on the "Host" page: 


![image](https://user-images.githubusercontent.com/19171465/50597862-dee52600-0e76-11e9-9c1d-a09489277078.png)

**Comment by mikeal** [comment]
In addition to just making things viewable on mobile, we need to have a deeper conversation about what our longer strategy is for mobile as the current experience w/ the code editor is not something that will work on mobile.

**Comment by olizilla** [comment]
There is the super helpful components section to the tachyons docs which shows various patterns for nav bars and lots of other layouts:

http://tachyons.io/components/#nav

The simplest thing here might be to just let the nav scroll horizontally like

http://tachyons.io/components/nav/list-overflow/index.html#

**Comment by zebateira** [comment]
We can close this @terichadbourne given this was tackled in #123 ?

**Comment by terichadbourne** [comment]
Yeah, we can call it good. If you use responsive setting on a laptop there's a width at which the nav will create a horizontal scroll before flipping to the hamburger, but when checking the phone views in dev tools it's showing up consistently as a hamburger, so this is probably too much of an edge case to worry about.
