### ISSUE TITLE
feature: Migrate routing to a "Lesson Route"

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#12]
Right now, you have to manually add a route for every step in your lesson.

We should move to a more dynamic route that:

1. Automatically detects how many lesson steps you have to lays them out.
2. Can alter the "Next lesson" button on the last step so that it bounces you back to the index instead.

**Comment by terichadbourne** [comment]
@mikeal Regarding the second step, note that I already made a conditional button that can bounce you back to the index if it's the last lesson in the series. However, it requires manually passing a `last: 'true;` in the right lesson of each series when you develop it. The [commit](https://github.com/ipfs-shipyard/proto.school/commit/35a329510f134467b49b8723d99aab0aa53049a1) is part of [this PR](https://github.com/ipfs-shipyard/proto.school/pull/63) that's awaiting another review before being merged.

I don't yet know enough about routing and Vue to tackle the first step, which I agree would be a more elegant solution (auto-detecting the number of lessons in the series), but I'm happy to attempt that once I'm more familiar.

**Comment by terichadbourne** [comment]
Update: You no longer have to add `last: true` in the last lesson of the series. The button code can correctly determine whether you're in the last lesson without that now. You do still have to create a route for each lesson in the current setup, so this issue is still open, to be addressed after 1.0.

**Comment by mikeal** [comment]
We can probably close this now, the main purpose of the issue has been resolved.
