### ISSUE TITLE
Feature/Discussion: Tutorial Builder Models

### ISSUE THREAD

**Issue by NukeManDan** [ProtoSchool/protoschool.github.io#140]
**Is your feature request related to a problem? Please describe.**
No - just a suggestion for future tutorial building

**Describe the solution you'd like**
Here is a cool project to build interactive tutorials for Ethereum: https://github.com/ChainShot/Builder
I am new to this tool, but on first look I think we can port some of the ideas/features it has for ProtoSchool

Would love to get some feedback on what others think about their solution compared to ours, as well as other tutorial building tools to look into / model after.

**Comment by NukeManDan** [comment]
@Dan-Nolan, @Roots2D... Would you be interested in collaboration on this at all?

**Comment by Dan-Nolan** [comment]
Absolutely, love the tutorials you've built out at Proto Schools! 

We have done some similar JS tutorials with [Merkle Trees](https://www.chainshot.com/lessons/5c36bf15143eed0017f579755ba1558bd9f997cd2e33eba7/) and [JavaScript Blockchain](https://www.chainshot.com/lessons/5c36bf15143eed0017f579755b3afd70d9f99763e5c4b4fe). Nothing yet with IPFS! I especially enjoyed all the written content that explains IPFS in great detail.

Hope you all don't mind, I quick drafted up a demo of what your tutorial content would look like run in our node JS environment. You can check it out [live here](https://www.chainshot.com/lessons/5c70579fff60ed0017eea6a75c70488c7f8d39a9ab46b9a4/). The test cases use a mock-version of ipfs, but a similar setup can be used with the real npm module. All of this content is open-source and can be forked from this [Content Repository](https://github.com/Dan-Nolan/ProtoSchool-Content).

**Comment by terichadbourne** [comment]
Thanks for the demo, @Dan-Nolan! 

We're not specifically looking for a new platform for ProtoSchool, but @NukeManDan I'd love to hear more about why you might find ChainShot more compelling than the existing system so I can better understand the need you see and what you might view as missing features.

**Comment by Dan-Nolan** [comment]
Sure thing! And certainly don't get me wrong, I'm not suggesting migrating your platform/content. I enjoyed the way your content is laid out and the direct integration with IPFS was an awesome touch! Quickly spun up the demo to see if it sparked any ideas.
