### ISSUE TITLE
Redirect porto.school to proto.school 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#145]
Per a Slack convo, @marcooliveira & @filipediasf have volunteered to make porto.school redirect to proto.school to help those who typo too fast. :) 🎉 

Per @eefahy "the domain owner (of porto.school) needs to unlock the domain and give us a transfer key (thankfully we already have a 1password vault for other domains we are currently transferring from Moxy folx) then I can kick off the transfer on our end"

Per @mikeal, "You have to wait 6 months after registering, we learned that trying to transfer proto.school :)"

Let's continue the conversation here about how to make this happen. 

See related issue on domain and deployment (#18) where @lgierth & @mikeal have been making plans to change the deployment of the full site.

**Comment by terichadbourne** [comment]
@marcooliveira @filipediasf @mikeal Just checking in to see if there's still a blocker here or if we could set up the redirect now from porto.school to proto.school. Thanks!

**Comment by filipediasf** [comment]
Hi @terichadbourne! I'm sorry but I'm not being working on Github so I'm not following this issue!

I'm happy to forward with the transfer of the ownership from MOXY to PL. I've already unlocked the domain and saved in the 1Password vault the transfer key. @eefahy can now follow up this.

Thanks!

**Comment by terichadbourne** [comment]
Thanks @filipediasf! 

@mikeal You still own proto.school, right? Shall we get that transferred to PL with help from @stongo and then get the redirect worked out from porto.school to proto.school?

**Comment by mikeal** [comment]
yes please! let me know what to do :)

**Comment by terichadbourne** [comment]
@mburns has offered to help us out with this! 🎉

**Comment by mburns** [comment]
Hi! Happy to handle this, just need the authorization key and I'll trigger the transfer.

I'm available on Slack/[keybase](https://keybase.io/mburns)

**Comment by filipediasf** [comment]
Thanks, @terichadbourne and @mburns. I will follow this conversation on slack!

**Comment by mburns** [comment]
@filipediasf and I touched base on Slack and were able to start this process. Domains are *transferring*..

**Comment by filipediasf** [comment]
I confirm the transfer! 🚀 @mburns could you please please confirm from your side?

**Comment by mburns** [comment]
Confirming the transfer completed. I've posted a PR to get the redirect working pending code review.

**Comment by terichadbourne** [comment]
Thanks @mburns! Have you also transferred proto.school from @mikeal to PL ownership already?

**Comment by mburns** [comment]
nope! I'll need a transfer code from @mikeal, and then can initiate the transfer.

**Comment by mburns** [comment]
http://porto.school/ is redirecting correctly.

Pinged mikeal to start the `proto.school` transfer to Gandi.

**Comment by mburns** [comment]
Transfer `55456975` is in-flight, it will show up in our shared Gandi account and get auto-renewed, etc. Thanks @mikeal !

@terichadbourne I think this ticket can be closed.

**Comment by terichadbourne** [comment]
Awesome! Thank you so much for your help with this, @mburns @mikeal @filipediasf!
