### ISSUE TITLE
Lesson Feedback: Blog - Lesson 2 - more info on debugging tools step

### ISSUE THREAD

**Issue by mowliv** [ProtoSchool/protoschool.github.io#149]
**URL of the lesson that's confusing:**
https://proto.school/#/blog/02

**What's confusing about this lesson?**

Opened developer tools in browser and pasted code in console, but got error "Uncaught SyntaxError: Illegal return statement" and don't know what to do to get it to work.

**What additional context could we provide to help you succeed?**
Remind me how to open dev tools (or install if I don't have it). Tell me where to paste code.

**What other feedback would you like to share about ProtoSchool?**

This is awesome! Just found out about it through ipfs newsletter. Great job! Exactly what's needed to help people get over the hump on this new stuff.

**Comment by terichadbourne** [comment]
Thanks for flagging this confusion @mowliv. Am I right to assume you were trying to follow these instructions when you did that? 

> Before modifying the code, please open the developer tools in your browser and submit the code in its current state. You’ll see the CIDs of the blog posts in the console. When you look at the console again after you’ve modified the code, you’ll see that the CIDs have changed. (Notice how we use CID.toBaseEncodedString() to access the CID as a string for purposes of console logging.)

You actually don't need to copy and paste anything here, but I see why this was confusing. First, open dev tools and click on "console." When we say "submit the code" in the quote above we mean to click the green submit button below the code editor, which runs the code that already contains the `console.log(message)` command in the pre-existing `run` function. That will make the relevant CIDs appear in your console. You then complete the exercise and hit submit again with the console still open to see how the CIDs have changed. 

Want to try it the way I've described and see if it makes sense? 

I'll assign this issue to myself to make sure we make those instructions more clear.

**Comment by mowliv** [comment]
Yes, those are the instructions I was trying to follow. And yes, it makes sense now. Just clarify that in the write-up and all will be well :) 

Thanks for your quick and friendly reply!

**Comment by terichadbourne** [comment]
We now have a feature (via #201) that allows us to display some logs to the user so they no longer need to use their own inspector:
![image](https://user-images.githubusercontent.com/19171465/57320397-cf981280-70cc-11e9-827f-e77e1247820d.png)

Closing this issue. Thanks again for the feedback @mowliv!
