### ISSUE TITLE
Feature: Support multiple choice questions

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#177]
Use this issue template to share a suggestion for a new feature or enhancement to be applied across the ProtoSchool site. (If you have feedback on a specific lesson, please use the Lesson Feedback issue template instead.)

**Is your feature request related to a problem? Please describe.**

@alanshaw has a new tutorial in mind for an upcoming event that would utilize multiple-choice questions instead of a code exercise.

**Describe the solution you'd like**
A new component would replace the exercise component and a builder of a lesson would have the option to build a multiple choice question with validation instead of a text-only lesson or lesson with code exercise or file upload + code exercise. 

The builder of the tutorial would need to establish: 
-  the question 
- some strings as the answers the user could select from
-  something indicating which is the correct answer
- error messages to display for each of the wrong answers (explaining why they're wrong) 
- success message to display for the correct answer (could help reinforce why it's right)

**Describe alternatives you've considered**

**Additional context**

Questions: 

Is it reasonable to force the builder to only work with radio buttons (single answer) as opposed to checkboxes (multiple answers) to simplify development? 

Should we define a set number of answers allowed (4?) or let the builder decide? 

Should the data go in as an array of objects to avoid a ton of strings? Something like this as options you'd put into the Vue file created for the lesson? 
{
question: "string question?",
answerOptions: [
{
answer: "string answer that's wrong",
correct: "false",
message: "friendly error message with hint to make them try again"
},
{
answer: "string answer that's right",
correct: "true",
message: "that's right because of this!"
},
{
answer: "string answer that's wrong",
correct: "false",
message: "friendly error message with hint to make them try again"
},
{
answer: "string answer that's wrong",
correct: "false",
message: "friendly error message with hint to make them try again"
}
]
}

Presumably this way we could loop through that data and print the options with how ever many answer letters are needed (A, B, C, D, etc.) and then use the "correct" field for validation purposes. 

The Lesson.vue component would get a v-if that only shows based on a new `isMultipleChoice` property that would be passed in (and replaces the exercise box). 

Would this meet your needs @alanshaw? 

How does this architecture strike you @olizilla @mikeal?

**Comment by alanshaw** [comment]
Yes this sounds great!

I don't think we should limit the number of choices.

I was thinking about an optional `maxSelections` prop and have the UI determine the appropriate controls to render....but I think initially single answer questions (radios) would be fine.

How about renaming `answerOptions` => `choices`?

`correct: "false"` - this should be a boolean not a string e.g. `correct: false`

**Comment by terichadbourne** [comment]
Totally agree on the boolean and the `choices` @alanshaw. Thanks for calling out those suggestions.

The reason I'd even consider capping a number of options would be pedagogical, not technical -- meaning I presume that a question with more than 4 or possibly 5 potential answers is just bad form and likely not very effective for learning -- but I could do that through documentation for authors rather than by imposing a technical limitation.

Part of the complexity added by allowing multiple checkboxes would be much more complicated error messages, in that different combos of selections would lead to different clues or explanations of what was wrong. Given our time constraints in preparing for the event in question, my gut is that focusing on just one potential UI - the radio button - seems like a reasonable MVP, and we could reassess needs down the road.

**Comment by fsdiogo** [comment]
This has been shipped in https://github.com/ProtoSchool/protoschool.github.io/pull/240.
