### ISSUE TITLE
Lesson Feedback: Blog - Lesson 1 (Link an author to a blog post using its CID)

### ISSUE THREAD

**Issue by iswarm** [ProtoSchool/protoschool.github.io#181]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
eg https://proto.school/#/blog/01

**What's confusing about this lesson?**
how to link an author to a blog post using its CID?
**What additional context could we provide to help you succeed?**

**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
@iswarm 

We previously did: 
```
  const samCid = await ipfs.dag.put({author: "Sam"})
```
and the `ipfs.dag.put()` method returns a CID (content address) for the data we put into IPFS. So we know that the value of `samCid` is a CID.

To link to that CID, we can create a field with a name and make its value a link to that CID. 

To add Sam as author of the post about trees, you can add a field called `author` with a value of `samCid`, like so: 

```
  const treePostCid = await ipfs.dag.put({
    content: "trees",
    author: samCid
  })
```

Does that help?

**Comment by terichadbourne** [comment]
@iswarm I'm closing this issue, but feel free to reopen if you have further questions or suggestions for improving the text of the lesson to make things more clear.
