### ISSUE TITLE
Lesson Feedback: Basics - Lesson 2 (Create a new node that's linked to an old one)

### ISSUE THREAD

**Issue by zebul** [ProtoSchool/protoschool.github.io#183]
https://proto.school/#/basics/02

Syntax example is confusing.  I was not sure how to complete the exercise given the code example below:

![image](https://user-images.githubusercontent.com/1380654/55662996-180e9880-57ce-11e9-9311-d6b59c7e87c7.png)

When I moved on to Lesson 3 of 3 the correct syntax became apparent.  I believe this lesson would be improved by adding 'ipfs.dag.put' to the code example as show below:

![image](https://user-images.githubusercontent.com/1380654/55663037-9408e080-57ce-11e9-8a72-32ab627e4bb0.png)

```
ipfs.dag.put{ 
    foo: barCid
}
```

**Comment by fsdiogo** [comment]
💯 agree with you @zebul.

Created a PR to fix it, what do you think @terichadbourne?

**Comment by terichadbourne** [comment]
Thanks @zebul & @fsdiogo. I want to ensure we're clearly distinguishing between what a named link **is** and how to add one. I'll make a quick edit to that PR with a proposal for addressing both more explicitly.

**Comment by terichadbourne** [comment]
@zebul Here's what the updated PR now produces. Would this address your concerns? 

![image](https://user-images.githubusercontent.com/19171465/55732411-ee31bd80-59e9-11e9-8055-b5bc6117ca3a.png)

**Comment by zebul** [comment]
@terichadbourne yes.  I think that adds clarity.  Thank you.

**Comment by terichadbourne** [comment]
Fabulous @zebul. Thanks again for the feedback.

@fsdiogo Could you please go ahead and merge this if you're also okay with my updates? Thanks!
