### ISSUE TITLE
Separate Decentalized Data Structures into 2 separate tutorials (general and DAG-focused) 

### ISSUE THREAD

**Issue by Frijol** [ProtoSchool/protoschool.github.io#185]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/data-structures/05

**What's confusing about this lesson?**
Why do we need to know about Merkle trees and DAGs?

**What additional context could we provide to help you succeed?**
Can you set up the "why" of these structures a bit more before describing them? What problems do they solve? Right now it feels a bit like reading a glossary– descriptive, but short on context.

This might also be a way to make the end of this tutorial less abrupt.

**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
@mikeal I agree with @frijol that it's not very clear why we're talking about Merkle Trees and DAGs. 

The lessons on content versus location addressing, trust, etc. feel super relevant as a primer regardless of what IPFS API you use. Is this lesson only here because of the DAG API? How could we make it more clear why this structure matters? Or should this lesson be separated out from the rest of the tutorial and be put into one of the DAG tutorials?

**Comment by mikeal** [comment]
Good point. We wrote this as a lead-in to the dag API. If we’re going to make it an introductory lesson for the IPFS stuff as well we can probably split it, and only recommend the dag content before that advanced lesson we’ve talked about that gets into how IPFS actually constructs the file data structures and obviously the dag tutorials.

Also, **Hi @Frijol!** good to see you (virtually) 🥳

**Comment by terichadbourne** [comment]
@mikeal @frijol I just spotted this video from Tara Vancil on why Merkle Trees matter to the decentralized web, and the thing it highlighted for me that I’m not sure we made apparent ourselves is how you can do partial verification. Should this be part of the narrative if we split the merkle dag bit out into its own tutorial? https://youtu.be/YIc6MNfv5iQ

**Comment by Frijol** [comment]
Yes I think that would be really helpful!

**Comment by terichadbourne** [comment]
@mikeal Should I expect new content to come out of IPFS Camp that would inform the DAG-y part of this, and therefore put off the content split until after camp?

**Comment by mikeal** [comment]
@alanshaw has been leading the the DAG-y tutorial, there’s some great content but I’m not quite how it might fit into ProtoSchool yet.

**Comment by terichadbourne** [comment]
There's a ton of relevant content for both portions of this to-be-split-in-two tutorial in @mikeal & @alanshaw's Core Course A: Understanding How IPFS Deals with Files from IPFS Camp 2019 ( [video](https://youtu.be/Z5zNPwMDYGg) | [slides](https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A/IPFS_Camp_Core_Course_A_Slides.pdf) | [course repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A)).

Specific action items as captured in the IPFS Camp content review (#261): 

- [ ] Use some of the pics or images from the verifiability section in the location v content addressing portion of our Decentralized Data Structures tutorial
- [ ] Add lots of the content from the Merkle DAG section to the latter part of the Decentralized Data Structures tutorial

**Comment by terichadbourne** [comment]
@mikeal suggested in a convo elsewhere today that we should relabel Decentralized Data Structures from IPFS to IPLD. That feels super appropriate for the second half (the Merkle DAG stuff) after we split it in two but the first half is very general intro to the concepts of content addressing / location addressing / hashing that’s probably not project specific. We may need to think about a more generic “dweb concepts” category for the first half of that. ¯\_(ツ)_/¯

**Comment by terichadbourne** [comment]
Just flagging here that we expect to separate the Merkle DAG stuff from this lesson out to become a part of new tutorial #412.

**Comment by terichadbourne** [comment]
@frijol Just wanted to give you a heads up that @mitchwagner is currently working on a new tutorial for the Merkle DAG stuff that will be coming out imminently. In the same PR we'll reduce the existing tutorial down to just focus on the location v content addressing bits. Feel free to load it up locally and peruse if you're interested!  see #582 

@mitchwagner Just flagging that this issue exists and may have some useful ideas, especially this video that could be listed in the resources: https://youtu.be/YIc6MNfv5iQ
