### ISSUE TITLE
Lesson Feedback: Blog - Lesson 7 (Traverse through all posts, starting with the most recent)

### ISSUE THREAD

**Issue by Frijol** [ProtoSchool/protoschool.github.io#187]
**URL of the lesson that's confusing:**
https://proto.school/#/blog/07

**What's confusing about this lesson?**
In the same vein as https://github.com/ProtoSchool/protoschool.github.io/issues/165, this lesson requires you to know Javascript syntax for while loops and pushing to an array

**What additional context could we provide to help you succeed?**

Maybe the best way to give JS-bonus information is e.g. "Hint: you will be using [while loops](//www.w3wchools/com/js/js_loop_while.asp) and [array methods](//www.w3schools.com/jsref/jsref_obj_array.asp) for this solution!"

**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
@frijol We've just merged a bunch of work on Blog lesson 7 that we believe addresses your feedback. I'll close this out, but please feel free to re-open if we haven't achieved what you were hoping for.

**Comment by Frijol** [comment]
thanks!
