### ISSUE TITLE
Make it possible to preview the state of a PR without running locally

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#190]
Per @olizilla, some of the repos for IPFS websites let you click a preview button to see a preview hosted on IPFS instead of having to download the code and run on localhost to do proofing. This would be particularly helpful for changes like the addition of chapters, or so that folks who suggested a tweak to our lessons can see our proposed changes with minimal effort. 

@fsdiogo Do you happen to know how that's implemented and whether there's anything that would prevent us from doing it here?

**Comment by olizilla** [comment]
https://github.com/ipfs-shipyard/ipfs-dns-deploy does the magic.

We might tune the set up a little for this org. As it uses secrets to get the job done (github token, ipfs cluster credentials, and a token to update dns) we have to be careful who gets to trigger jobs that could expose those secrets.

We could add those secrets just to the protoschool website repo config rather than the org... the significant consideration is we can only enable these builds for folks that are explicitly members of the repo.

It's a huge boost to have preview urls on your PRs, but right now you can't get them for contributors who aren't part of the org / repo... as it would be possible for anyone with permission to trigger a CI build to craft a PR that exposes those secrets.

cc @scout

**Comment by terichadbourne** [comment]
@olizilla Do you mean that contributors who aren't part of the org/repo can't *create* the previews when submitting a PR or that they can't *view* them if an admin submitted the PR that created them? If someone without powers to create the preview submits a PR, can an admin click a button that makes the preview get created?

It's only the website repo that I was envisioning having this feature. My GH vocab is probably not up to snuff, but there are a few really common use cases here: 

- A chapter organizer who is an org member but has admin privileges only on their chapter repo, not the website repo, submits a PR to the website repo (via a fork) to add their chapter to the website. One of the website admin repos needs to review and approve it.

- An external contributor (who may or may not be a member of the broader org, depending whether they're also a chapter organizers) reports an issue with a lesson. An admin on the website repo is the one to submit a fix as PR and wants that external contributor to have an easy way to view the proposed solution.

- An external contributor (who may or may not be a member of the broader org, depending whether they're also a chapter organizers) reports an issue with a lesson and submits their own PR (via a fork) to fix it. An admin on the website repo needs to review and approve it. 

- Website repo admins work together on larger updates with multiple edits to the same PR and need to proof along the way.

**Comment by olizilla** [comment]
in it's current form, only PRs that are from branches would have the circle-ci build run on them, which in practice means, only users who are added as members of the repo would get preview links added to their PRs. The problem gets worse if you use CI on circle to enforce any other standards / or run any automated tests... as those would only be run for PRs from repo memebers, not PRs from external contributors... its not ideal but we could dodge that issue by running regular CI on travis or github actions.

> A chapter organizer who is an org member but has admin privileges only on their chapter repo, not the website repo, submits a PR to the website repo (via a fork) to add their chapter to the website. One of the website admin repos needs to review and approve it.

they would **not** get a preview.

> An external contributor (who may or may not be a member of the broader org, depending whether they're also a chapter organizers) reports an issue with a lesson. An admin on the website repo is the one to submit a fix as PR and wants that external contributor to have an easy way to view the proposed solution.

they would get a preview

> An external contributor (who may or may not be a member of the broader org, depending whether they're also a chapter organizers) reports an issue with a lesson and submits their own PR (via a fork) to fix it. An admin on the website repo needs to review and approve it.

they would **not** get a preview

> Website repo admins work together on larger updates with multiple edits to the same PR and need to proof along the way.

they would get a preview.

**previews are tied to how the PR gets created.** If the PR is from a branch then all changes on the PR would get a preview. Only repo members with write access, can created or update a branch.

**Comment by olizilla** [comment]
@mikeal do you have the keys to proto.school dns? I don't see it in the PL infra teraform screeds.

**Comment by mikeal** [comment]
@olizilla yes I do I initially registered it and we were blocked from transferring it because, apparently, with this TLD you can’t transfer right after registering. Should be fine now though, I can unlock and transfer it whenever people want :)
