### ISSUE TITLE
No option to resubmit code when correct answer changes

### ISSUE THREAD

**Issue by Frijol** [ProtoSchool/protoschool.github.io#208]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/basics/03

**What's confusing about this lesson?**
The submit button is gone forever once you solve it!
Y'all changed what the solution is

from:
```js
/* globals ipfs */

const run = async () => {
  let cid = await ipfs.dag.put({ test: 1 })
  let cid2 = await ipfs.dag.put({ bar: cid })
  return await ipfs.dag.get(cid2, '/bar/test')
}

return run
```

to 

```js
/* globals ipfs */

const run = async () => {
  let cid = await ipfs.dag.put({ test: 1 })
  let cid2 = await ipfs.dag.put({ bar: cid })
  return await ipfs.dag.get(cid2, '/bar/test').value
}

return run
```

but I can't hit submit anymore to test my own code! I can only do it by clicking "View Solution" and deleting all my code.

**What additional context could we provide to help you succeed?**

**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
We did recently notice some confusion around what that lesson asks for and updated both the description of the assignment and the correct solution. 

Are you saying that it had remembered your old solution after marking it passed previously and now there’s only a next button?

**Comment by fsdiogo** [comment]
> Are you saying that it had remembered your old solution after marking it passed previously and now there’s only a next button?

Just tested this, and yes, after a lesson is marked as passed, even if you go back and change the code you will only get the option of `Next`, even with the wrong code. Hitting `Reset Code` is the only thing that takes brings back the `Submit` button and revalidates everything again.

**Comment by Frijol** [comment]
^ yep! Exactly.

**Comment by terichadbourne** [comment]
@zebateira let's circle around and check the status of this bug. I suspect we've already solved this one.

**Comment by zebateira** [comment]
Yes, I can confirm this is now working properly.

![Screen Cast 2020-09-18 at 10 39 29 AM](https://user-images.githubusercontent.com/2353186/93583207-6fd99900-f99b-11ea-9088-cc2d0854a5e0.gif)
