### ISSUE TITLE
Bug: No intuitive way to go back once clicking "View Solution" button

### ISSUE THREAD

**Issue by jimcal** [ProtoSchool/protoschool.github.io#211]
**Describe the bug**
Once the user click `View Solution`, there is not an intuitive way to go back the solution input by the user.

**Does this bug apply to a specific lesson or tutorial, or does it appear to be sitewide?**
Currently, this applies to all the scenarios that has the button `View Solution`

**Expected behavior**
I understood that this feature is a much welcome feature, and was just merged two days ago. However, it would be nice to compare solution to the original answer by the user.

**To reproduce**

- Go to any lesson.
- Click on 'View Solution'
- Other than reset code (which would wipe out the user's input) there is no other way to go back to the state contains the solution user previously enter.

**Comment by jimcal** [comment]
_Fully expect someone said this is a feature not a bug._

**Comment by fsdiogo** [comment]
Hi @jimcal, thanks for pointing this out.

I definitely can see the benefits of having the ability to compare the user's code with the solution.

A way to solve this would be to have the solution appear in a split window, like you can do in any good code editor, but I have no idea if that's possible in monaco editor.

I'll take a look and see what I can do.

**Comment by fsdiogo** [comment]
Potential solution in https://github.com/ProtoSchool/protoschool.github.io/pull/215, check it out.

**Comment by jimcal** [comment]
@fsdiogo excuse me for the late response, but this looks great! Look forward to this getting merged!

**Comment by fsdiogo** [comment]
@jimcal it has been merged! Thanks for the feedback!
