### ISSUE TITLE
Feature: Allow light formatting of `logDesc` when displaying results to user

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#216]
When I use the awesome new logging feature built by @fsdiogo and described [here](https://github.com/ProtoSchool/protoschool.github.io/blob/code/README.md#display-results-to-the-user-optional), I wish I could pass in either HTML or markdown rather than just a string so that I could do some light formatting, like boldface or italics, in my text. In the example below you can see that I'd especially benefit from code formatting (my `` isn't affecting the display). 

![image](https://user-images.githubusercontent.com/19171465/57035820-ecda6600-6c20-11e9-81c4-63aac254ae92.png)

@fsdiogo Is there a straightforward way to do this? The ways I think of offhand would be (a) innerHTML or (b) yet another md file that pulls in to the Vue file, but I haven't played with either option yet.

**Comment by terichadbourne** [comment]
@fsdiogo -  @olizilla also noted this issue during our pairing last week and thought allowing markdown would be the best solution so we can create code blocks using backticks where needed. Maybe this is something we could pair on so I could learn how to get HTML to understand markdown?

**Comment by fsdiogo** [comment]
> ... and thought allowing markdown would be the best solution so we can create code blocks using backticks where needed.

Hmm, I like this idea 🤔 

Because right now the syntax highlighting is for JSON only (`lang="json"`):

```html
<div v-if="output.test.logDesc" class="lh-copy">{{output.test.logDesc}}</div>
  <highlight-code lang="json" class="output-log">
    {{output.test.log}}
  </highlight-code>
</div>
```

Using `marked()` as we're using with the exercises description et al, it would give us the ability to highlight multiple languages.

Want to pair on this @terichadbourne?

**Comment by terichadbourne** [comment]
Sounds great @fsdiogo. Sent you a calendar invite for tomorrow but we can reschedule if the time doesn't work.
