### ISSUE TITLE
Bug: Lines breaking mid-word in success/fail messages

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#232]
@fsdiogo It looks like the success/fail area is trying to do full justification and is splitting words partway through instead of wrapping to the next line. Do you know off hand how to quickly fix that? 

![image](https://user-images.githubusercontent.com/19171465/59364296-a3436780-8d04-11e9-9bda-f0f661a5bae9.png)

**Comment by fsdiogo** [comment]
Yes, I'll PR a fix in a minute.
