### ISSUE TITLE
Lesson Feedback: Mutable file system - Lesson 11 (Remove a file or directory)

### ISSUE THREAD

**Issue by DrawnWren** [ProtoSchool/protoschool.github.io#241]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/mutable-file-system/11

**What's confusing about this lesson?**
This lesson doesn't teach much. I generally had the same feeling going through most of your tutorials. I really would like to know what the effects of the ipfs.file.rm() method are. How has the content changed, what happened to the old directory (isn't this whole thing immutable?), what's different about the representation? I had the same questions in the blog lesson. It felt more like a poorly documented api check-list than a lesson per se

**Comment by terichadbourne** [comment]
Thanks for sharing @DrawnWren! It's always a fine line choosing the right depth to go into on any topic, and feedback from users is really helpful. 

If you haven't seen them yet, there are two courses from IPFS Camp that I think would offer some deeper perspective of the type you're looking for as to what's going on under the hood. I called them both out in this recent blog post, where you can find links to videos and slide decks:  https://blog.ipfs.io/2019-09-18-ipfs-camp-course-videos/

I have a separate issue open to incorporate some of the recent IPFS Camp material into ProtoSchool to address these types of questions, so I'm going to close this issue, but please feel free to re-open if you find useful materials to recommend or have specific content suggestions to propose.
