### ISSUE TITLE
Better describe in-browser nodes in MFS - Lesson 2

### ISSUE THREAD

**Issue by NukeManDan** [ProtoSchool/protoschool.github.io#250]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
eg https://proto.school/#/blog/01

**What's confusing about this lesson?**
>We're creating your IPFS node behind the scenes so you can focus on the content of our lessons, but eventually you'll need to learn to host your own node locally by installing IPFS and running a daemon in your terminal. When you're ready to experiment, you can find instructions for installing IPFS and initializing your node in our docs.

Maybe better wording would be We create a local instance of a node (in browser only) that will be lost when you reload the page, as we create a new one each time. And link to the documentation of [JS-IPFS](https://github.com/ipfs/js-ipfs). To keep *persistent* files on your machine, you much have a stand alone instance of IPFS outside the browser. To make them available to the network, you must be running a daemon.

Does that seem closer to the facts here? Or am I missing something? :grin:

**Comment by terichadbourne** [comment]
Hey, @NukeManDan. Really appreciate the feedback!  It looks like we changed this wording when we created the Regular Files API tutorial. Mind taking a look at the wording [here](https://proto.school/regular-files-api/03) and seeing if it addresses your needs? If so, we can copy it over to MFS and do a double-check for other places that might have the old language.

**Comment by NukeManDan** [comment]
I still think "behind the scenes" is a bit confusing and could be reworded to indicate that you are using js-ipfs to create a node that is hosted entirely in the browser, and when you close the tab/window, that is cleaned up and no longer exists. That data on proto.school is not persisted longer than you are on the page of a lesson for that reason - you can't expect to find your "uploads" latter on IPFS.
