### ISSUE TITLE
Add links from IPFS & IPLD docs & websites to ProtoSchool

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#260]
Need to review the documentation that exists on IPFS / IPLD sites for topics already covered by ProtoSchool tutorials and link to ProtoSchool where appropriate. This will be primarily in IPFS Files API and IPFS DAG API documentation.

**Comment by terichadbourne** [comment]
@alanshaw I've put in PRs to link from the DAG API and Files API docs, as well as the summary of all the APIs. (See above for links to those PRs in relevant repos.) Can you think of other spots in current docs where either API is explained that should be updated as well?

**Comment by terichadbourne** [comment]
@mikeal I added a PR to IPLD to include links to relevant ProtoSchool tutorials on the IPFS DAG API, but I don't have any rights in that repo so wasn't able to tag you as a reviewer. Mind taking a look? https://github.com/ipld/ipld/pull/77 

Please let me know if you can think of other spots across IPLD repos where such links would be appropriate (I already added to IPFS DAG API docs).

**Comment by alanshaw** [comment]
What about linking to protoschool from ipfs.io and js.ipfs.io?

**Comment by terichadbourne** [comment]
> What about linking to protoschool from ipfs.io and js.ipfs.io?

@alanshaw @olizilla Any specific thoughts on the best place to highlight ProtoSchool on ipfs.io? One thought I've had is adding a second button here that would be something like "Explore ProtoSchool tutorials": 

![image](https://user-images.githubusercontent.com/19171465/61382575-0a5fb900-a87b-11e9-8d77-52d1b2650ec5.png)

The footer's another option but it already feels overcrowded to me: 
![image](https://user-images.githubusercontent.com/19171465/61382701-4135cf00-a87b-11e9-8f6d-b61958196f04.png)

For js.ipfs.io, one option is to add the ProtoSchool tutorials to the list [here](https://github.com/ipfs/js-ipfs/tree/master/examples#js-ipfs-examples-and-tutorials) so that people will find it if they hit the Tutorials tab: 
![image](https://user-images.githubusercontent.com/19171465/61383257-4d6e5c00-a87c-11e9-971f-44903d29f81c.png)

Another would be to change "Try it out below!" to "Try it out below or explore our tutorials on ProtoSchool!" with an in-line link: 
![image](https://user-images.githubusercontent.com/19171465/61383081-fec0c200-a87b-11e9-9501-a0891aaa5772.png)

Any suggestions before I start a PR?

@mikeal Would you like ProtoSchool linked from ipld.io as well? Suggestions on where it would be most appropriate / least disruptive?

**Comment by terichadbourne** [comment]
We've now merged all of our PRs across multiple repos to add links to ProtoSchool from ipfs.io, js.ipfs.io, IPFS API docs and example repos, and IPLD examples repo. (Easiest way to see these edits is to scroll up and click the links to issues next to the purple "merged" labels.) 

@mikeal Would you like anything from the IPLD website itself? (Nothing pops out at me as the perfect spot to insert it but I'd be happy to brainstorm with you.)

I've leave this issue open until Wednesday to collect any more suggestions for IPFS/IPLD sites/resources to link to ProtoSchool from. If nothing else appears I'll close this out and we can add new issues for further suggestions. As we create new tutorials and edit existing ones, we'll make a point of updating inbound links where appropriate.

**Comment by mikeal** [comment]
*sigh*

I don’t think anyone right now is happy with the IPLD website but we haven’t prioritized doing anything about it this quarter. I also don’t see a good place for it but, knowing that we’re overdue for a redesign, I think the best thing to do is log an issue in the repo about this and we’ll add it to the list of things to make sure we consider in the next version of the site.

**Comment by terichadbourne** [comment]
Thanks, @mikeal. I've logged an issue for the IPLD website here: https://github.com/ipld/website/issues/60

**Comment by terichadbourne** [comment]
Closing this issue based on the merged work completed across a variety of sites/repos: 

- ipfs.io website
   - [Add ProtoSchool links to ipfs.io #318](https://github.com/ipfs/website/pull/318)
- js.ipfs.io website
   - [chore: add protoschool link & fix libp2p references #264](https://github.com/ipfs/js.ipfs.io/pull/264)
- js-ipfs examples readme
   - [Add js-ipfs ProtoSchool tutorials #2273](https://github.com/ipfs/js-ipfs/pull/2273)
- interface-js-ipfs-core repo
   - DAG spec: [Add links to ProtoSchool DAG API tutorials #500](https://github.com/ipfs/interface-js-ipfs-core/pull/500/files)
   - Files spec: [Edit formatting & link MFS to ProtoSchool #499](https://github.com/ipfs/interface-js-ipfs-core/pull/499/files)
- js-ipfs-http-client readme
   - [Link to ProtoSchool tutorials #1047](https://github.com/ipfs/js-ipfs-http-client/pull/1047/files)
- IPLD readme
   - [Link to ProtoSchool tutorials on IPFS DAG API #77](https://github.com/ipld/ipld/pull/77/files)
