### ISSUE TITLE
OKR Epic (Q3): ProtoSchool 💻

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#265]
Please use this epic for ProtoSchool-related tasks of the IPFS Docs WG. Due to filtering limitations, it lives in the ProtoSchool repo.

To add an issue from an the docs repo to this card, you'll need to remove any repo-specific filters so that this epic and your issue appear in ZenHub at the same time. 

You can see the [ProtoSchool Q3 OKRs](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q3.md) (which also include things on the community front unrelated to documentation/website) in our roadmap repo.

**Comment by jessicaschilling** [comment]
@terichadbourne, are we OK to close this issue since Q3 is done?
