### ISSUE TITLE
Lesson Feedback: Mutable file system - Lesson 8 (Move a file or directory)

### ISSUE THREAD

**Issue by adamSellers** [ProtoSchool/protoschool.github.io#272]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/mutable-file-system/08

**What's confusing about this lesson?**
Documentation Bug - the instructions describe the flags for files and directories backwards.. quote below.. 

> IPFS has a type property that you can use to determine whether it's a file or a directory; its value is 0 for directories and 1 for files.

**Comment by fsdiogo** [comment]
Good catch, thanks @adamSellers! I'll fix it!
