### ISSUE TITLE
Lesson Feedback: Mutable File System - Lesson 8 (Move a file or directory)

### ISSUE THREAD

**Issue by Npizza** [ProtoSchool/protoschool.github.io#293]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/mutable-file-system/08

**What's confusing about this lesson?**
At exercise, on the template that we have to complete I can not understand exactly what is happening. 
You give this to help us:

> 
>   const filesToMove = // create an array of files to be moved (no directories)
> 
>   const filepathsToMove = // create an array of the paths of those files
> 
>   // move all the files in filepathsToMove into /some/stuff
> 

From my understanding you what to create a array with the file names, then a array with the path for each file and then loop for every slot in the array and move it. But on the solution you give this answer that confuse me a little bit.

> const filepathsToMove = rootDirectoryContents.filter(file => file.type === 0).map(file => '/' + file.name)
>   await ipfs.files.mv(filepathsToMove, '/some/stuff')
> 
>   //  // alternatively, wrapping multiple mv calls into a single async function with await:
>   //  const filesToMove = rootDirectoryContents.filter(item => item.type === 0)
>   //  await Promise.all(filesToMove.map(file => {
>   //    return ipfs.files.mv('/' + file.name, '/some/stuff')
>   // }))

I understand that you provide two different solutions to this problem but my javascript knowledge is basic so if you could make it more clear I would really appreciate it.

So if I have understood correctly you create a variable **filepathsToMove**   but I am not sure what **rootDirectoryContents.filter(file => file.type === 0).map(file => '/' + file.name)** returns.
I can guess it is a list of filepaths like this example **await ipfs.files.mv(['/source-file-1.txt', '/source-file-2.txt'], '/destination-directory')** but I am not sure...

Also I noticed that line:

>   await Promise.all(files.map(f => ipfs.files.write('/' + f.name, f, { create: true })))

I am not exactly sure what it is doing,  I guess that somehow creates the files on the IPFS node but I can not understand step by step what it is happening.

    
**What additional context could we provide to help you succeed?**
Some more information or references  about the solutions that you suggest.

**What other feedback would you like to share about ProtoSchool?**
I really enjoy your tutorials I am looking forward to complete all your tutorials.

**Comment by terichadbourne** [comment]
Thank you so much for sharing this feedback @Npizza! We definitely picked a more advanced JavaScript option in that solution mostly as a space-saver, but the same thing can be accomplished with more lines of code and more familiar methods. So that I can explain this in the most helpful way, can you first tell me which of these JavaScript concepts are already comfortable for you, if any? 
- forEach
- filter
- map
- Promise.all

**Comment by terichadbourne** [comment]
@npizza Just checking in to see if you still have questions on this one. I'm going to close the issue for now, but please feel free to reopen and share more about which JavaScript concepts you're already familiar with (see above) if you'd like more help. Thanks!
