### ISSUE TITLE
Epic 4A: Review and ID IPFS Camp Content

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#306]
Please use this epic for relevant ProtoSchool-related tasks of the IPFS Docs WG. Due to filtering limitations, it lives in the ProtoSchool repo.

To add an issue from an the docs repo to this card, you'll need to remove any repo-specific filters so that this epic and your issue appear in ZenHub at the same time. 

You can see the [ProtoSchool Q4 OKRs](https://github.com/ProtoSchool/roadmap/blob/master/okrs/2019-q4.md) (which also include things on the community front unrelated to documentation/website) in our roadmap repo.

____________

## 4A. Complete review of IPFS Camp content identifying how it can be applied to create new ProtoSchool tutorials, enhance existing ones, or improve the docs.ipfs.io site
<img src="https://img.shields.io/static/v1?label=Priority&message=P0&color=red">

**_Find all issues associated with this epic [here](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+4a%22+)._**

### Deliverables
Generate the review and turn into prioritized GitHub issues (in ProtoSchool and docs repos)

### Owners
- @terichadbourne & @dominguesgm 

### Context
Please see the Documentation & Developer UX Working Group's [Q4 2019 OKRs](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909) for information on how this epic fits into the team's larger goal structure for the quarter.

**Comment by jessicaschilling** [comment]
@terichadbourne -- are we OK to close this epic? Thanks!

**Comment by terichadbourne** [comment]
Yep. Just closed our survey issue and included a link to a bunch of newly opened issues for content integration that we can keep knocking off in Q1.
