### ISSUE TITLE
What is Pinned?

### ISSUE THREAD

**Issue by Islandassets** [ProtoSchool/protoschool.github.io#308]
How to attach picture/video/website to Ravencoin assets?
I will continue the lessons.

Thank you

**Comment by terichadbourne** [comment]
Hi @Islandassets. I'm afraid I'm not sure what this question refers to. I'm not familiar with Ravencoin and it's not a topic covered by ProtoSchool. Closing out this issue as it appears to be in the wrong repo.

If you do have a question about a specific ProtoSchool lesson, please open a [new issue using the lesson feedback template](https://github.com/ProtoSchool/protoschool.github.io/issues/new?assignees=&labels=lesson-feedback&template=lesson-feedback.md&title=Lesson+Feedback%3A+%5BLesson+Title+%28URL%29%5D) so we can best assist. Thanks!
