### ISSUE TITLE
Feature: Submit code snapshot after unexpected error while validating

### ISSUE THREAD

**Issue by dominguesgm** [ProtoSchool/protoschool.github.io#315]
When a user submits code in a Coding Lesson, and our validation returns a generic error message, the user gets no additional feedback about their answer other than "it's incorrect", without any hint of what they should try to do differently.

A way to make use of this scenario to improve the lessons and their validation would be a link/submission form which would create a Github issue, with a predefined template for this very purpose, containing a copy of the code of the user which led to the generic error feedback.

This link/form would only appear after a solution submission which resulted in a generic error feedback.

**Comment by terichadbourne** [comment]
note also #319 that could be addressed in the same edits, to remind people that "view solution" exists

**Comment by dominguesgm** [comment]
This package seems relevant for the purpose of pre-building the issue for the user from a copy of the user code:

https://github.com/sindresorhus/new-github-issue-url

**Comment by terichadbourne** [comment]
closed via #334
