### ISSUE TITLE
Improve button contrast

### ISSUE THREAD

**Issue by lidel** [ProtoSchool/protoschool.github.io#317]
> @ericronne  mentioned this problem in WebUI and now I cannot unsee it everywhere :eyes: :sweat_drops: 

### Problem

Buttons have low contrast and look "disabled" and literally look the same when "disabled" and "enabled":

- Disabled
  - ![off-2019-10-31--15-23-14](https://user-images.githubusercontent.com/157609/67955565-12a5ef00-fbf3-11e9-86d3-2fe7d9a627e6.png)

- Enabled + hover
  - ![on-2019-10-31--15-23-33](https://user-images.githubusercontent.com/157609/67955564-120d5880-fbf3-11e9-9c9a-44c1e0324fb4.png)
  - ![2019-10-31--15-47-03](https://user-images.githubusercontent.com/157609/67957540-11c28c80-fbf6-11e9-9fd1-d2702b792de4.png)

### Proposed change

It would be useful to change background of "enabled" buttons to something like `bg-navy` from [ipfs-css](https://github.com/ipfs-shipyard/ipfs-css):

![Screenshot_2019-10-31 ProtoSchool](https://user-images.githubusercontent.com/157609/67957846-84cc0300-fbf6-11e9-8994-2f716b35ce0e.png)

**Comment by terichadbourne** [comment]
@lidel Do you remember where you were / what you were doing when you got a disabled button that looks like this? We do have at least one case where we disable it (when you haven't yet uploaded files, but that case contains a hover state with a message that makes it abundantly clear why you can't click. 

(I'm open to color changes also, just want to make sure we also know when/why it's happening in case there's other stuff to address.

**Comment by ericronne** [comment]
Fyi disabled buttons don't have to meet the 4.5:1 guideline mark.
https://www.w3.org/TR/WCAG21/#contrast-minimum

**Comment by lidel** [comment]
@terichadbourne it was `/#/regular-files-api/05` (i cropped the screenshot, below is full version of disabled button): 

![2019-11-01--13-34-45](https://user-images.githubusercontent.com/157609/68025174-77715000-fcac-11e9-98eb-47c02ace8cee.png)


What I meant that disabled button looks ok, the problem is contrast of active ones :)

**Comment by ericronne** [comment]
I'd recommend that the inactive button color be a tint of the active button, rather than a different color altogether. So if the submit button will be blue when active, it could look something like this when inactive (alphaed back blue for the fill, alphaed back white text):
![y](https://user-images.githubusercontent.com/9259185/68030483-91e50280-fc87-11e9-8561-c63c7ce4387b.png)

**Comment by terichadbourne** [comment]
Thanks for the suggestions @lidel & @ericronne. @dominguesgm could you take a stab at this one this week?

**Comment by terichadbourne** [comment]
closed via #342
