### ISSUE TITLE
Lesson Feedback: Mutable File System - Lesson 2 (Check the status of a directory)

### ISSUE THREAD

**Issue by awllc** [ProtoSchool/protoschool.github.io#318]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/mutable-file-system/02

**What's confusing about this lesson?**
I copied the sample code and am trying to do the root directory instead of "stuff," but no matter how I edit it, I still keep getting that the result doesn't look right. 

**What additional context could we provide to help you succeed?**
Could you give us the code for the root directory instead of 'stuff' if we're supposed to do the root directory in the exercise? Or let us press to have the right answered entered for us after X tries, so we can go on even if it isn't returning the correct result the way we're doing it?

**What other feedback would you like to share about ProtoSchool?**
Just started

**Comment by terichadbourne** [comment]
Hi @awllc! 

It sounds like you may not yet have spotted the option to view the solution, which you can find under each coding challenge. It's accessible regardless of how many times you've tried to solve the problem. Clicking here will display the correct answer in a box underneath the code editor, and you can always copy and paste the code from there if needed. I've circled it in the screenshot below: 

![image](https://user-images.githubusercontent.com/19171465/67968774-5b06e200-fbde-11e9-94c7-b104932455c1.png)

In short, when you use `stat`, you need to pass in a string representing the directory you want to inspect. So, taking the sample in the exercise as an example, you'll be replacing `/stuff` with `/` to get the root directory instead of the stuff directory. 

After you check out the solution code, I'd love to hear what code you'd been trying previously so we can incorporate other hints if needed. Sounds like it would also be a good idea for us to add a note about the "view solution" feature in our more generic error messages. 

Thanks!

**Comment by awllc** [comment]
I am clicking to view the solution. The stats aren't showing in the solution, and also the solution has stopped updating based on my changes in the top box. I've refreshed the page and reset the Try It box, but the view solution still stays on one of my previous attempts.

**Comment by terichadbourne** [comment]
Here's what I see when I submit a wrong answer and then click to view the solution: 

![image](https://user-images.githubusercontent.com/19171465/67970454-6576ab00-fbe1-11e9-9461-dadcd389f95a.png)

Does that black box with correct code not appear when you click "View Solution"? (Its contents will never change, though you can hide and unhide them. They're just there for you to reference as needed. 

You should be able to click "Reset Code" at any time (unless you're already viewing the starter code) to delete your current attempt and replace it with the starter code that was there when you first arrived on the page so you can begin again.)

When you see a red bar under that with error feedback after you hit "Submit," you should still be able to edit the code box and hit "submit" again to try something new, which will generate new success or error feedback in a green or red bar there. 

If what you see doesn't sound like what I'm describing, could you please share a screenshot and tell us what browser you're using so we can try to identify the bug?

**Comment by awllc** [comment]
I'm getting this:

![image](https://user-images.githubusercontent.com/29823558/67971024-66f4a300-fbe2-11e9-9da3-ffe4d8e3e4ef.png)

**Comment by terichadbourne** [comment]
Great! Looks to me like you've updated your code correctly. If you click the "Submit" button now to validate your new code and scroll down beneath that black solution box (or click to hide it), what do you see?

**Comment by awllc** [comment]
"Oops! You forgot to return a result :(

**Comment by awllc** [comment]
![image](https://user-images.githubusercontent.com/29823558/67971286-e97d6280-fbe2-11e9-91c0-0dc44f640563.png)

**Comment by terichadbourne** [comment]
Ah, sorry, I missed the error when I looked at it. See the difference between your line 4 and line 4 of the solution? You need to add `return` there. (This is a JavaScript thing, not an IPFS thing.)

**Comment by terichadbourne** [comment]
Throughout the lessons you'll see `return run` at the end, and you never need to edit it. All of your code, including any results you're asked to return, needs to happen inside that run function.

**Comment by awllc** [comment]
Oh! I was totally misunderstanding the show/hide solution box. I thought I was seeing a preview of the return of my formula above, not what I was supposed to be putting into the first box! Got it. LOL

Thanks.

**Comment by awllc** [comment]
I need more sleep.

**Comment by terichadbourne** [comment]
No worries! In some of the lessons we will indeed show you the results of the code you've run (or something else we find interesting) after you submit successful code, but it will appear down below in a new "Inspect Results" section: 
![image](https://user-images.githubusercontent.com/19171465/67971695-9eb01a80-fbe3-11e9-833e-125de7595bc7.png)

**Comment by awllc** [comment]
Awesome. Thanks again.

**Comment by terichadbourne** [comment]
No problem! Hopefully things will be smooth sailing in the next lessons. :)
