### ISSUE TITLE
Mention the "View Solution" option when providing catch-all error messages

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#319]
As seen in https://github.com/ProtoSchool/protoschool.github.io/issues/318, some folks aren't spotting the option to view the solution. Our custom error messages usually provide good feedback specific to known/suspected errors, but when we default to  a more generic "something's wrong" message, it would be great to mention in it that the view solution option is available.

**Comment by terichadbourne** [comment]
@dominguesgm can you please review both the  code branch and error-handling branch (and the newer branch off of it) to confirm we've already taken care of pointing this out in the messages for both user-caused and validation-caused issues? If so, let's close this one out. Thanks!

**Comment by dominguesgm** [comment]
Yup, your last commit in #334 mentions the solution in the errors. Closing the issue.
