### ISSUE TITLE
Define JSON/BSON in Data Structures - Lesson 4

### ISSUE THREAD

**Issue by rfdiazpr** [ProtoSchool/protoschool.github.io#335]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
eg https://proto.school/#/blog/01

**What's confusing about this lesson?**
Just an improvement.  JSON and BSON are mentioned but not define.

**What additional context could we provide to help you succeed?**
"JavaScript Object Notation is an open-standard file format or data interchange format that uses human-readable text to transmit data objects consisting of attribute–value pairs and array data types."  [Wikipedia](https://en.wikipedia.org/wiki/JSON)

"BSON is a computer data interchange format. The name "BSON" is based on the term JSON and stands for "Binary JSON". It is a binary form for representing simple or complex data structures including associative arrays, integer indexed arrays, and a suite of fundamental scalar types. BSON originated in 2009 at MongoDB."  https://en.wikipedia.org/wiki/BSON

**What other feedback would you like to share about ProtoSchool?**
Great project!

**Comment by terichadbourne** [comment]
Thanks for the suggestion! We've taken a look and feel that the details of JSON and BSON aren't important to the key point here: that you can link data of a variety of formats. The sentence you're referring to expresses this with acronyms that will be familiar to those with more technical proficiency, and the following sentence expresses it with more everyday language (cats, dogs, articles, GIFs, etc.) that will work for others. We believe the concept of "variety of formats" is addressed sufficiently either way, and that it would be distracting to dig into explanations of those formats when they're not essential to our key message. 

I'm going to close this issue out, but please keep the feedback coming! It's very much appreciated!
