### ISSUE TITLE
Update IPFS docs links when legacy site is deprecated

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#339]
Once the content of https://docs.ipfs.io/ is replaced by the content of https://docs-beta.ipfs.io/, we should search our codebase for links to docs.ipfs.io and check that they're all going to valid entries, updating URLs if needed. (Much of the content has been regorganized and will have new URLs.) 

I've added a reminder in the [docs deprecation plan](https://hackmd.io/-JU3CcXgSgmcXWszyku2PA) for us to circle back to this when the time comes.

**Comment by terichadbourne** [comment]
Heads up that this is docs upgrade is scheduled to happen on Friday.

**Comment by zebateira** [comment]
I can work on this tomorrow then.

**Comment by terichadbourne** [comment]
Thanks! Just need to do it after they actually transition, so we can keep an eye on the convo in the #ipfs-docs channel.

**Comment by terichadbourne** [comment]
@zebateira Just a heads up that this transition happened today, so this one's unblocked.

**Comment by zebateira** [comment]
I just checked all the links and everything is working fine since the links have redirects configured. I'll create a PR anyways to change the links so the docs page loads faster.
