### ISSUE TITLE
Improve strategy for validating code exercises by using Error Codes instead of relying on Error Messages from IPFS lib

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#343]
To continue the previous discussion on #337, I think it is worth considering that we make validation code use the error codes instead of the error messages so that our logic becomes more robust.

If we go forward with this, it needs to be standardized and documented, but at the same time, we could apply this new approach iteratively on new tutorials only, and when possible we could update old ones and add tests for them as well so we are more confident that we are not breaking anything.

**Comment by terichadbourne** [comment]
This one requires input from @alanshaw before moving forward, because the way error codes work in IPFS is (to my understanding) a bit atypical and also in flux (a variety of open issues or PRs to improve the system, I believe). See the full discussion in #337 for more on my concerns.

**Comment by terichadbourne** [comment]
Based on our chat with Alan we can go ahead with this when we have the time, changing validation code to reference IPFS error _codes_ instead of _strings_.
