### ISSUE TITLE
Lesson Feedback Regular Files API - Lesson 5 (Add files in a directory)

### ISSUE THREAD

**Issue by joeyguerra** [ProtoSchool/protoschool.github.io#352]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
eg https://proto.school/#/blog/01

**What's confusing about this lesson?**
I entered the correct code but got an error about wrapWithDirectory.

**What additional context could we provide to help you succeed?**
I guess just let me continue to the next lesson when there's an error.

**What other feedback would you like to share about ProtoSchool?**
I love it.

**Comment by zebateira** [comment]
hello @joeyguerra !
Thank you for submitting the feedback!
Could you share the code you submitted? Should still be there. Thank you!

**Comment by carlbordum** [comment]
Perhaps this is what I ran into in #356. Is it fixed now @joeyguerra?

**Comment by joeyguerra** [comment]
That’s it!!! Thank you.

**Comment by zebateira** [comment]
Perfect! Thank you @joeyguerra and @carlbordum 🙏
