### ISSUE TITLE
Feature: Enable markdown on multiple-choice answer text

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#364]
In order have more pleasant experience on multiple-choice lessons, we should enable markdown to the answers text. This would allow to highlight some text, with bold italic, etc.

Ref: https://github.com/ProtoSchool/protoschool.github.io/pull/359#pullrequestreview-353151422

![image](https://user-images.githubusercontent.com/2353186/73840683-1c627280-4832-11ea-96ed-92fd5d11ae6e.png)

**Comment by terichadbourne** [comment]
This has been addressed and will be closed when we merge #359
