### ISSUE TITLE
Feature: Cache and track toggle status for hiding coding tutorials

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#366]
Since introducing our lesson/tutorial type icons and adding the toggle button to hide coding tutorials (#346), we now have the opportunity to cache the toggle state so that if a user has previously chosen to hide coding tutorials they'd find them hidden when returning to the tutorials page. (Currently it loads/reloads with all tutorials visible.)

An additional bonus would be if we created a parameter in the URL that would set the toggle to hide the coding tutorials, so that we could give someone a URL to go to to see just the non-coding ones.

**Comment by zebateira** [comment]
Consider adding tracking to it as well so we can understand its usage.

**Comment by zebateira** [comment]
In summary:

 - [ ] Add caching
 - [ ] Add a query parameter that matches the current selected value
 - [ ] Add tracking for each toggle press
