### ISSUE TITLE
Lesson Feedback%3A Data Structures - Lesson 3 (The decentralized web: Content addressing)

### ISSUE THREAD

**Issue by michals2** [ProtoSchool/protoschool.github.io#377]
**URL of the lesson that's confusing:**
https://proto.school/#/data-structures/03

**What's confusing about this lesson?**
There's a typo: `Crytographic` should be `Cryptographic `

**What additional context could we provide to help you succeed?**

**What other feedback would you like to share about ProtoSchool?**

**Comment by zebateira** [comment]
Nice catch @michals2 ! Thank you 🙏
