### ISSUE TITLE
Upgrade Cypress to 4.0 to support cross-browser testing

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#386]
Cypress recently announced v 4.0 which supports testing in MS Edge and Firefox in addition to Chrome. However, it has breaking changes so we'll need to explore thoroughly before upgrading. 

- [Announcement](https://cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/)
- [Migration Guide](https://docs.cypress.io/guides/references/migration-guide.html#Migrating-to-Cypress-4-0)
- [Cross-Browser Testing Guide](https://docs.cypress.io/guides/guides/cross-browser-testing.html#Continuous-Integration-Strategies)

**Comment by zebateira** [comment]
We've upgraded to `v5` on #562, so next I'll add more browser testing
