### ISSUE TITLE
Bug: Loading GitHub default 404

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#388]
Just spotted this note from @zebateira on an older PR that's already been merged. When we changed the routing I believe we created fewer cases in which we can load our own 404, so we'll need to set up an alternative via GitHub for cases where, for example, the `#` is omitted from the URL. 

> Ah nice catch!
> 
>  _Interestingly hitting a GitHub-generated 404 and not our own - will this case be fixed by the routing PR you have in progress by any chance?_
> 
> hm no, unfortunately, when you access any route besides / you will get github's 404.
> but we can customize it using: https://help.github.com/en/github/working-with-github-pages/creating-a-custom-404-page-for-your-github-pages-site

**Comment by zebateira** [comment]
Actually, if i'm not mistaken, only when you omit the `#` will you get Gitbhub's 404 page, and this was happening before the refactor since this is a problem with the current build system.

**Comment by zebateira** [comment]
We can probably create a page that redirects to `/#/404` when github catches a 404.

**Comment by terichadbourne** [comment]
Are you envisioning using JavaScript within script tags in the HTML file to change `window.location`? Or some other method?

I started trying to play with this but I can't preview it properly. 

On the real site, leaving out the # does this: 
![image](https://user-images.githubusercontent.com/19171465/74981482-5621a480-5400-11ea-830d-ef49f4cbae92.png)


But on localhost it adds a #/ to the end and shows the homepage. ¯\_(ツ)_/¯ 
![image](https://user-images.githubusercontent.com/19171465/74981599-8cf7ba80-5400-11ea-944d-aace34ef46d4.png)

Both the live site and localhost go to our custom 404 page if you try to access `/#/nonsense`.

**Comment by zebateira** [comment]
@terichadbourne this is a problem with the current build system: we are only building one single `index.html` file that serves the root path `/`, so the 404 needs to be configured within github pages (server side).

**Comment by zebateira** [comment]
After researching this issue a bit I stumbled upon a really cool hack that enables no-hash routing in github pages! It's working locally: #393

**Comment by terichadbourne** [comment]
Quick update: since #393 is more broad and affects a number of interrelated URL-ish issues (anchor tags, SEO, hash v history, hosting options, separate meta tags per page, redirects from GH 404), we've decided to instead (for now) create a 404.html to redirect the GitHub default as mentioned earlier in this trail and circle back later to ensure we're making the right decision for those interrelated issues.
