### ISSUE TITLE
Localization strategy?

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#39]
We need to figure out how community members can contribute localizations to the lessons.

**Comment by lidel** [comment]
@mikeal we should add it to https://www.transifex.com/ipfs/public/ :)

Steps I see:

1. Create a PR which moves English strings to separate source files, preferably in JSON-ICU format (to make it framework-agnostic and integrate with Transifex without conversion step). 
   Some prior art:
    - In new WebUI we're using `i18next` with `i18next-icu`, [the setup is quite straightforward](https://github.com/ipfs-shipyard/ipfs-webui/blob/a67135c0a5041ed5c7a6d5216e9b664cb5336726/src/i18n.js).
    - There is an open PR adding i18n to IPLD Explorer that you can check as well: https://github.com/ipfs-shipyard/ipld-explorer-components/pull/1/
    - Those apps use React, but `i18next` bits will be mostly the same. I see there is also a helper for Vue: [@panter/vue-i18next](https://www.npmjs.com/package/@panter/vue-i18next), but I had no experience with it.
1. In the same PR add `.tx/config` and create a project at Transifex (ping @lidel)
1. Merge to master
1. Set up Transifex to automatically check source strings from `master` for updates 

Step 1 is a chore but If you create PR with that, I can set up the rest :)

For more info about Transifex part, see References in https://github.com/ipfs/ipfs-gui/issues/50

**Comment by terichadbourne** [comment]
Closing in favor of #268 which I created accidentally as a duplicate. Have moved the detailed notes over there for reference.
