### ISSUE TITLE
Blog lesson 1 isn't clear enough

### ISSUE THREAD

**Issue by vmx** [ProtoSchool/protoschool.github.io#40]
Blog Lesson 1 "Basic linking" isn't clear enough. People tried to insert a link (`{'/': samCid.toBaseEncodedString()}` into the dag first and then use that CID.

It also wasn't clear that you should *edit* the existing `puts()` calls.

It also wasn't clear if the author should linked to the blog post or the other way round.

**Comment by terichadbourne** [comment]
Look at this again after refactoring for the new API

**Comment by terichadbourne** [comment]
@vmx Could you please review the revised https://proto.school/#/blog/01 and see if the new wording (and change to use the new CID link API makes this all clear now? I'm comfortable closing out the issue if you are.

**Comment by vmx** [comment]
Thanks @terichadbourne, I think it is clear now.
