### ISSUE TITLE
Add support for virtual event listings

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#409]
A few tweaks we can make to support community leaders who'd like to explore virtual events: 

- [ ] Tweak form to allow "Virtual" in place of location
- [ ] Add timezone support, since location will no longer be an indicator of time zone

**Comment by terichadbourne** [comment]
@zebateira Thinking through the data collection portion of this, I think the smallest change we could make to the spreadsheet would be to add an "is this event hosted virtually" checkbox and switch the existing city and country fields to optional. I believe this would just add one more column to the end of the resulting spreadsheet. Am I right to assume I shouldn't start messing with the form until we've adjusted our data fetching code?

**Comment by zebateira** [comment]
@terichadbourne I don't think there's an issue when new fields are added only. If they are re-ordered or removed then it messes up the data parsing.
