### ISSUE TITLE
New Tutorial: How verified storage works in Filecoin 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#414]
In discussing potential Filecoin content with @mishmosh, she suggested a multiple-choice tutorial on how verified storage works. Some content ideas to include: 

- Proofs of space-time
- How they work 
- How to verify your data and how long it's been stored by reading the immutable chain
- Teach how to examine by looking for output labelled `cmd-p` or `cmd-d`
- Potential questions could include something like "Here's a CID and 3 recent storage deals. When was content most recently proven for this data?"  (Until we have full JS support,  this probably needs to be us pretending you just ran a command and we're showing you the output.)

Starling abstracts parts of this process. 

Would love feedback on additional topics that would be part of this tutorial, common misconceptions we should try to address, etc.

**Comment by terichadbourne** [comment]
Some additional feedback/suggestions paraphrased from Ben Fino-Radin: 
- Easy for us to explain the concept of verified storage at the high level, but when it comes down to the specific hash values (CommR, CommD, CommRstar) there's confusion about which one means what – important to communicate to communities accustomed to MD5, SHA, etc
- Explaining the difference between proof-of-work vs proof-of-stake would be very helpful to ease objections that blockchain is bad fo the environment ( the kinds of proofs Filecoin uses don't use as much energy as normal crypto mining)

**Comment by mishmosh** [comment]
Common misconceptions: encryption. Filecoin uses lots of **crypt**ography for proving storage, but it doesn't have **encryption** built in.

**Comment by terichadbourne** [comment]
@mishmosh @dignifiedquire @zebateira and I met today to work on a more thorough content outline, which is accessible here: https://docs.google.com/document/d/1BVTzOUZ9QHpuT2mNUhNwu-jWmnmiUPN0Ke_8zFv_QBc/edit?usp=sharing
