### ISSUE TITLE
User profile survey

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#424]
After implementing the 3-question on-screen tutorial satisfaction survey (#423), we plan to create a longer survey in Google Forms designed to learn more about the profile of our typical user. Users who've completed the tutorial feedback will be asked if they can spare the time to fill this one out. Data collected will include questions such as whether a user is a developer, how new they are to coding and to dweb, how they learned about ProtoSchool, etc. 

Blocked by #423, which we'll launch on its own and then adapt to lead optionally to this longer survey. 

Once you've completed this longer survey, we'll cache your status so you won't see the request a second time unless visiting in a new browser or otherwise clearing your cache. 

Planning notes at: https://docs.google.com/document/d/1z-QA-bV-6YnZW0HQgvLNLhEwFakgsjls8inYB0gZtCE/edit?usp=sharing

Will share a Google Forms draft when ready.

**Comment by zebateira** [comment]
This is the design I've come up with. The arrow indicates that it's an external link.

![image](https://user-images.githubusercontent.com/2353186/84143786-146c4680-aa4f-11ea-8bfc-3f88cb78a465.png)

In the Figma: https://www.figma.com/file/lnCeFi9O1PIgxMdKcgHIcM/ProtoSchool-Website?node-id=102%3A5

**Comment by terichadbourne** [comment]
I think this works visually @zebateira, thanks! For the copy, how about something like... 

```
Thank you! 

We really appreciate your feedback on this tutorial! 

**Have a few more minutes to help us out?** We've created a quick survey to learn more about our users so we can better meet their needs.

Go to Survey --> 
``` 

Maybe you could mock it up this way and then we can ask our UX pals for feedback on the wording and design?

**Comment by zebateira** [comment]
Updated:

![image](https://user-images.githubusercontent.com/2353186/84166874-6754f680-aa6d-11ea-8613-d18c7cd49761.png)

**Comment by mishmosh** [comment]
s/their needs/your needs ?

**Comment by mishmosh** [comment]
And maybe speak to what's new between the feedback they already gave & additional questions in the form?
