### ISSUE TITLE
Lesson Feedback%3A Mutable File System - Lesson 2 (Check the status of a directory)

### ISSUE THREAD

**Issue by unstopableme** [ProtoSchool/protoschool.github.io#431]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**What's confusing about this lesson?**
on line 4 i typed the solution but keep getting an error so I am confused and not able to get pst lesson 2.
I am a beginner very green. Ok never mind i found out the solution at first i delated the part where it says your code goes here.  On lst attempt i typed solution before text on line four and compleated lesson two. On to lesson 3. till next time 

unstopableme.

**Comment by terichadbourne** [comment]
Glad you got this working, @unstopableme! Hope you're enjoying the tutorial!
