### ISSUE TITLE
Bug:  Bad render on Safari

### ISSUE THREAD

**Issue by joaosantos15** [ProtoSchool/protoschool.github.io#434]
**Describe the bug**
https://proto.school/#/tutorials has a bad render on Safari v13.0.5 

**Does this bug apply to a specific lesson or tutorial, or does it appear to be sitewide?**
Only noticed on the tutorials page https://proto.school/#/tutorials 

**Expected behavior**
Normal render

**Screenshots**
Safari on the left, Chrome on the right
![Screenshot 2020-04-30 at 00 21 41](https://user-images.githubusercontent.com/10178757/80689077-aeda8100-8ac4-11ea-8633-a8104f24e81c.jpg)

**To reproduce**

- Open Safari browser
- Go to https://proto.school/#/tutorials

**Desktop (please complete the following information):**
- OS: MacOS 10.15.3
- Browser: Safari 13.0.5 
- Version: 13.0.5

**Comment by zebateira** [comment]
thank you @joaosantos15! fixed this in #435 
should be ok now.
