### ISSUE TITLE
Lesson Feedback%3A Blog - Lesson 4 (Add a new blog post linked to an author and tags)

### ISSUE THREAD

**Issue by bhanuone** [ProtoSchool/protoschool.github.io#439]
**URL of the lesson that's confusing:**
[https://proto.school/#/blog/04](https://proto.school/#/blog/04)

**What other feedback would you like to share about ProtoSchool?**

I am not able to work on the code challenges. I've checked the browser console and noticed some error logs

![Screenshot 2020-05-14 at 7 46 15 PM](https://user-images.githubusercontent.com/3231946/81945337-9ec1b600-961b-11ea-8e1c-ccabb13cd8f5.png)

**Comment by terichadbourne** [comment]
This for flagging this @bhanuone! Is this the only lesson you're having trouble with, or are all code challenges causing problems for you? Mind telling us what browser you're using? 

cc @zebateira

**Comment by bhanuone** [comment]
Yes. only this one @terichadbourne

**Comment by zebateira** [comment]
I tested in Brave and it worked fine. Those error messages should not affect this code challenge.

@bhanuone if you can't workout the solution we can help you with it, just let us know what seems confusing about the lesson.
In the end you can always use the "View Solution" button at the bottom left to see the final solution.

![image](https://user-images.githubusercontent.com/2353186/81960212-7ed4c700-9608-11ea-99c8-2ecfd6abd6ae.png)

Let us know if we can help any further.

**Comment by zebateira** [comment]
@bhanuone closing this. if you need any help with the coding challenges let us know!
