### ISSUE TITLE
Feature: Add project name to cards on homepage

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#442]
We display the project name on the tutorials page but not the homepage cards. Let's find a good spot to add it so we can remove those IPFS: prefixes from lesson titles. 

![image](https://user-images.githubusercontent.com/19171465/83270182-1c4a0200-a196-11ea-980e-988a9cbdb861.png)

**Comment by zebateira** [comment]
Here's an option:

![image](https://user-images.githubusercontent.com/2353186/84166158-6e2f3980-aa6c-11ea-83a4-5e120e5accb3.png)

**Comment by terichadbourne** [comment]
Looks good to me! The only other thing I can think of is bottom right, but it might look silly with the logo being at different distances from the right with each project name a different length.

**Comment by zebateira** [comment]
> The only other thing I can think of is bottom right, but it might look silly with the logo being at different distances from the right with each project name a different length.

Agreed, I don't think it would work either.
