### ISSUE TITLE
Feature: Build multiple choice questions in ProtoWizard

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#445]
After we get our CLI published (#440), let's circle back and make it possible to build a multiple-choice quiz through the CLI instead of just by editing the JS file.

**Comment by zebateira** [comment]
Sounds good.
Another improvement we could do is to change the file from javascript to json.
This way folks without coding experience would be able to navigate the json file better than the javascript one. And they would have less possible issues with eslint.

**Comment by terichadbourne** [comment]
Note to self: Can't use ` quotes in JSON
