### ISSUE TITLE
Lesson Feedback%3A Verifying Storage on Filecoin - Lesson 4 (Proof-of-Spacetime (PoSt))

### ISSUE THREAD

**Issue by porcuquine** [ProtoSchool/protoschool.github.io#455]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**

https://github.com/ProtoSchool/protoschool.github.io/issues/454

**What's confusing about this lesson?**

>Rather than checking for the original data, it checks the encoded version (the CommR), which during the Proof of Replication was proved to be an encoding of the original data. Since the CommR is a type of merkle tree called a Directed Acyclic Graph (DAG), this can be done with a merkle inclusion proof.

Some adjacent but independent points:
- `CommR` is not the root of the merkle tree built over the replica.
- The root of that merkle tree is not the tree itself.
- The reference to DAGs is out of place.

I tried to just rewrite the above to say what I think you mean, but how to do that will somewhat depend on changes to the previous explanation also, unfortunately. So let me at least explain what you need to make a fuller explanation, and you can choose the right level of granularity and use it consistently.

- `CommR` is a commitment to the replica, but it is a hash of a tree used only in PoRep *and* of the commitment we call `CommRLast` — which doesn't appear on chain. `CommRLast` is indeed the merkle root of the replica (i.e. the uniquely encoded copy of the original data).
- Since `CommRLast` is a merkle root — the result of having constructed a merkle tree over the replica, proof of each random check can be provided with a merkle incusion proof.

I think you may want to elide some of the details of how `CommR` is constructed and used, but please try to avoid doing so in a way suggesting that `CommR` is actually the merkle root of the replica. This is not true and could confuse someone seeking a deeper understanding.

**What additional context could we provide to help you succeed?**

**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
Thanks so much for the feedback @porcupine! 

@mishmosh I'd love your take on how best to address these concerns with the right level of beginner-friendliness.

**Comment by mishmosh** [comment]
How about this? (Bold is to show new words only, and should not be bold in the tutorial.)

Rather than checking for the original data, it checks for the merkle root of the **uniquely** encoded ~version~ **copy** (generated during Proof of Replication, explained in Lesson 3) ~was proved to be an encoding of the original data~. **This merkle root is also known as CommRLast, and it is checked** ~Since the CommR is a type of merkle tree called a Directed Acyclic Graph (DAG), this can be done~ with a merkle inclusion proof.

**Comment by porcuquine** [comment]
Hmmm. The problem is we're not really checking a 'merkle root' at all. The merkle root is *used* to check the data. We have to prove knowledge of CommRLast, given CommR as a public input. Having done that, we use CommRLast as part of the merkle inclusion proofs which prove actual knowledge of the spot-checked (challenged) leaf nodes of the replica.

This wasn't intended to be a replacement sentence. I know I'm providing more and more information. The idea is to give you enough accurate explanation that you can eventually choose a consistent simplification that works in context.

**Comment by mishmosh** [comment]
The quiz answers will also need to be changed:

Option 3:
> It regularly checks that all encoded data is still present on the Filecoin network.

Option 4:
> It regularly checks to ensure that a random section of encoded data is present in the right location, comparing against the publicly known CommR.

**Comment by mishmosh** [comment]
Okay, I've tried to simplify to an outline. Is this true?

1. Proof of Spacetime doesn't check all the data, it just checks a subset.
2. The subsets aren't totally random bytes; they're selected leaf nodes, or subgraphs, of the replica's DAG.
3. During each Proof of Spacetime, the miners take [inputs including the previously generated CommR] and perform [an action]. This is compared against [____]. (Not sure I fully understand what the inputs/outputs are, if CommRLast is the root of the entire replica but PoSts are run on subsets only.)
4. Because hashing is one-way, the ability to generate the expected CommRLast (?) is proof that the miner is still storing the original data correctly.
5. PoSt is a type of merkle inclusion proof (or are there merkle inclusion proofs a _part_/phase of PoSt?). (I think we can eliminate the merkle inclusion proof concept altogether, though, since it's not critical to the overall lesson.)

**Comment by porcuquine** [comment]
> The subsets aren't totally random bytes; they're selected leaf nodes, or subgraphs, of the replica's DAG.

This doesn't really make sense. They are randomly selected nodes: these are 'leaves' of the tree, or just nodes of the replica. If you divide the whole replica into 32-byte chunks, these are the nodes. There's not really a DAG left anymore once you have a replica.

> Not sure I fully understand what the inputs/outputs are, if CommRLast is the root of the entire replica but PoSts are run on subsets only.

Every node of the replica has the same root, because the root is the apex of a tree built over all of it. The word 'subset' in your sentence applies because not every node is checked (that would be a huge and expensive proof) — only some randomly selected nodes.

> Because hashing is one-way, the ability to generate the expected CommRLast (?) is proof that the miner is still storing the original data correctly.

Yes: ability to generate it with a proof of the expected structure. (This clarification is probably not necessary, but so you understand: I could 'generate' CommRLast through hashing without the original data by providing a shorter merkle inclusion proof. This might only prove I am actually storing a tiny part of the tree. In order to prove I am storing the leaf in question, the merkle inclusion proof has to be long enough and of the correct shape.)

> PoSt is a type of merkle inclusion proof (or are there merkle inclusion proofs a part/phase of PoSt?). (I think we can eliminate the merkle inclusion proof concept altogether, though, since it's not critical to the overall lesson.)

PoSt is many merkle inclusion proofs bundled together into a single SNARK.

**Comment by terichadbourne** [comment]
@porcuquine Trying to reconcile these two comments you've shared: 
> the commitment we call CommRLast — **which doesn't appear on chain**. CommRLast is indeed the merkle root of the replica (i.e. the uniquely encoded copy of the original data).

> We have to prove knowledge of CommRLast, given CommR as a public input.

If CommRLast isn't saved to the chain during PoRep, just confirming it is only CommR that PoSt checks against. Basically, you couldn't have gotten the CommR without having first had the CommRLast so when we see the CommR we know you once had the CommRLast? Or does PoSt actually have direct access to CommRLast?

**Comment by porcuquine** [comment]
Miners have to save `CommRLast` and use it as a private input to PoSt. They prove, without revealing its value, that they know of a root for the replica which both agrees with their inclusion proofs *and* can be used to derive the publicly-known `CommR`.

**Comment by terichadbourne** [comment]
Thanks so much for the continued clarification @porcuquine. @mishmosh  and I have drafted a revision in PR #464 and would love your feedback as to whether we've succeeded at actually getting our heads around this and relaying it accurately enough to not mislead people. 😂
