### ISSUE TITLE
Bug: Tracking of submitWrongChoice showing N/A as choice

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#469]
Need to check our logic for the submitWrongChoice event in Countly. I was expecting to see human 1,2,3 options here for which wrong choice was selected but instead see an NA. Could mean something's broken or could mean we're counting 0,1,2.

This comes from the Quiz and Lesson components, esp the handleRadioChoice method in Lesson.

Might be wise to also pass the string value of that answer field to avoid future confusion.

![image](https://user-images.githubusercontent.com/19171465/86390203-a7bb2500-bc65-11ea-9632-0f6939fd7678.png)

![image](https://user-images.githubusercontent.com/19171465/86390272-c3bec680-bc65-11ea-9225-d3899b7c433b.png)

**Comment by zebateira** [comment]
So I checked countly, and I think this is an issue with countly's data representation that does not match what we need with that query you ran.
If I go to the events tab, I see the following:

![image](https://user-images.githubusercontent.com/2353186/86485974-08c02700-bd52-11ea-8332-1dda03f39bac.png)

(To see this data go [here](https://countly.proto.school/dashboard#/5d25fd49db14b4435e4432e2/analytics/events/key/submitWrongChoice) and select the segment `wrongChoice`).

In your graph the selected type of data could be one of `Visitors`, `Times`, `Sum`, etc.

![image](https://user-images.githubusercontent.com/2353186/86486136-6eacae80-bd52-11ea-8e20-8c40df028bf2.png)

I'm not sure what that means. Does it mean the total about of unique visitors that submitted that event (when `Visitors` is selected)?
So I don't understand what `N/A` means in this context as well.

**Comment by zebateira** [comment]
@terichadbourne I just checked the stats and I think you are right that countly is showing `N/A` to represent the `0`. This only happens in this drill option, but it works on the events tab.

**Comment by zebateira** [comment]
@terichadbourne just heard back from the Countly team: they fixed the issue. Looking good now 👌 

![image](https://user-images.githubusercontent.com/2353186/86904564-ce1b0d80-c108-11ea-9926-8e64ca900a0f.png)
