### ISSUE TITLE
Confirm we're not double-logging tutorialPassed or lessonPassed events

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#470]
Countly shows that users are passing each tutorial more than once per visitor: 

![image](https://user-images.githubusercontent.com/19171465/86794990-1a981780-c03b-11ea-901d-b2225c37f576.png)

Let's revisit our tracking code with fresh eyes to confirm we're tracking both`lessonPassed` and `tutorialPassed` at appropriate times and avoiding sending repeat values from the same visitor.

**Comment by zebateira** [comment]
So I debugged this and concluded that both the `lessonPassed` and `tutorialPassed` events are being sent to countly multiple times per user. Bellow is a detailed explanation of the current tracking logic:

### `lessonPassed` event

- For **text lessons**, we are always sending the tracking event when we click the `Next` button.
- For **quiz lessons**, we send an event every time a user changes the state of the quiz from null/wrong to correct. So the first initial event is sent when the user gets the answer right the first time, but also if the user changes to an incorrect answer and back to the correct answer.
- For **code challenges** (with or without file upload), the same behaviour from the quizzes applies: we send an event everytime a user changes the state of the answer from null/wrong to correct.

So effectively, **the user can track the `lessonPassed` event multiple times** for each lesson, independently of the lesson type.

### `tutorialPassed` event

- For **text lessons**, after a user finishes a tutorial and goes back to a lesson, clicking "next" it sends both the `lessonPassed` and `tutorialPassed` events
- For **quiz lessons**, after a user finishes a tutorial and goes back to a lesson, change the answer to a wrong choice and back to the right answer sends both the `lessonPassed` and `tutorialPassed` events
- For **code challenges**, same thing as the quizz lesson: changing to a failure state back to the correct solution sends off the `tutorialPassed` event again.

To tackle this issue I'll add an extra logic to track these events to local storage:

1. When tracking an event, take a record of that in LS
2. If the record is found in LS, skip tracking
