### ISSUE TITLE
Lesson Feedback%3A Verifying Storage on Filecoin - Lesson 2 (Preparing and transferring data)

### ISSUE THREAD

**Issue by NukeManDan** [ProtoSchool/protoschool.github.io#481]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/#/verifying-storage-on-filecoin/02
**What's confusing about this lesson?**
typo or things that needs explaining: "bitpadded"

**What additional context could we provide to help you succeed?**
a link to explain or typo fix ;)

**What other feedback would you like to share about ProtoSchool?**
keep on rockin it :)

**Comment by NukeManDan** [comment]
found in this section: https://github.com/ProtoSchool/protoschool.github.io/blob/code/src/tutorials/0007-verifying-storage-on-filecoin/02.md#preparing-data-for-storage

**Comment by zebateira** [comment]
I think we can use `bit padded` or `bit stuffed` here.
But it might need an explanation for it indeed.

**Comment by terichadbourne** [comment]
Would this help, @NukeManDan & @zebateira? cc @mishmosh 

`The IPLD DAG is then serialized to a CAR file and bit padded to make a Filecoin Piece. (Bit padding adds extra bits to make the piece conform to a standard size.) This piece has a unique piece CID, also known as a CommP (Piece Commitment).`

**Comment by NukeManDan** [comment]
lgtm for now! :grin: 
Hope that these topics become more clear here and in the main docs as things get flushed out. :crossed_fingers:

**Comment by mishmosh** [comment]
lgtm. Thanks for the suggestion @NukeManDan and keep them coming.
