### ISSUE TITLE
Bug: Good SNARKS are here needed video unavailable

### ISSUE THREAD

**Issue by alanshaw** [ProtoSchool/protoschool.github.io#501]
![Screenshot 2020-07-29 at 18 47 52](https://user-images.githubusercontent.com/152863/88834790-3d49c600-d1cc-11ea-82a9-c1dd6a13f2bf.png)

**Comment by zebateira** [comment]
Thank you @alanshaw 🙏 
For some reason the link was lowercased 🤷
