### ISSUE TITLE
More SEO Improvements

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#506]
We need to improve our SEO stats. To do this we can improve the following:

- [x] Only have one `h1` tag per page (ATM he have 2 in some pages)
- [x] Add `title` and `alt` to all images (missing in some)
- [x]  Let homepage have a different format for its title
- [x] Sitemap
    - Add trailing slashes to the sitemap paths
    - Add more properties to each sitemap entry: `priority`, `lastmod` and `changefreq`
- [x] Allow to override html title tag without the `| ProtoSchool` suffix

This is what's missing considering the changes in #505.

**Comment by terichadbourne** [comment]
Other things not yet done at time of merging #505: 

- [ ] Let homepage have a different format for its title
- [ ] Set tutorial landing pages as canonical links for lesson pages

**Comment by zebateira** [comment]
> Set tutorial landing pages as canonical links for lesson pages

Regarding this, I did some research and this is what I found:

https://moz.com/learn/seo/canonicalization:
> 5. Be careful canonicalizing near-duplicates
When most people think of canonicalization, they think of exact duplicates. It is possible to use the canonical tag on near-duplicates (pages with very similar content), but proceed with caution. There’s a lot of debate on this topic, but It’s generally ok to use canonical tags for very similar pages, such as a product page that only differs by currency, location, or some small product attribute. **Keep in mind that the non-canonical versions of that page may not be eligible for ranking, and if the pages are too different, search engines may ignore the tag.**

https://yoast.com/rel-canonical/: 
> Using rel=canonical on not so similar pages
While I wouldn’t recommend this, you can use rel=canonical very aggressively. Google honors it to an almost ridiculous extent, where you can canonicalize a very different piece of content to another piece of content. However, if Google does catch you doing this, it will stop trusting your site’s canonicals and thus cause you more harm…

https://www.gsqi.com/marketing-blog/google-ignore-rel-canonical-different-content/:
> Google’s Algorithms Can Ignore Rel Canonical When URLs Contain Different Content

I think that we have great content on the lesson pages which should be used as we discussed with Andrew.
Maybe the callout for when a user lands on a lesson directly "Start from the beginning!" or similar would be enough to help a user and even though it's not ideal, we'd still get more inbound traffic because of the great content lessons provide.

I suggest:

 - Adding lessons pages to the sitemap
 - Adding callout to start the tutorial from the beginning

Would like Andrew's input again on this.

**Comment by terichadbourne** [comment]
Summoning @andrew (see above). :)

Another question would be what happens if you don’t add a canonical link but also don’t add to the sitemap. Does it still get indexed but not surfaced at those times when Google seems to present a mini site map in its listing?

**Comment by andrew** [comment]
> I suggest:
> 
>     Adding lessons pages to the sitemap
>     Adding callout to start the tutorial from the beginning
> 
> Would like Andrew's input again on this.

:+1: on this, it'll be interesting to see how well those individual pages get indexed and how much direct traffic they get, plus how many people go back to the start of the tutorial from landing on a lesson page

**Comment by zebateira** [comment]
New UI callout tracked here: #523
