### ISSUE TITLE
Feature: Footer

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#515]
Footer to include: 

Social Links
- [ ] GitHub
- [ ] Twitter
- [ ] newsletter call-out?
- [ ] Email? currently we push to "Get in touch" on contribute so they'll try GH or whatever's appropriate first

Related projects: 
- [ ] IPFS
- [ ] Filecoin
- [ ] PL
- [ ] IPLD ? 
- [ ] Multiformats ? 

Feedback mechanisms (see also #426) 
Currently we're using 2 separate footers within tutorials - One to collect feedback on specific lessons and another to collect feedback on specific tutorials. We also have the 3-question tutorial satisfaction survey at the end of each tutorial, followed by a link to the user survey. It's important that if we we remove the current footer versions of lesson/tutorial feedback that we still have some kind of "Feeling stuck?" etc to prompt for GH submission re both specific lessons and overall tutorials. 

Do we want a bit of about-style text here that would add to our character counts for real content on each page?

**Comment by terichadbourne** [comment]
Was just speaking with Marta in Legal about an unrelated topic and realized that we currently only have our Apache/MIT licenses in GitHub, not a content license visible to website viewers. She told me that all PL content is licensed as [Creative Commons 3.0](https://creativecommons.org/licenses/by/3.0/) so it can be used and transformed but only with attribution, including links to the source. 

As an example from the [ipfs.io](https://ipfs.io/) footer: 
![image](https://user-images.githubusercontent.com/19171465/91491848-a9c6ec00-e882-11ea-855c-f7d1af82c28d.png)

We don't currently call out PL connections on our site. She said if we were intentionally trying to not to promote it we could list the attribution as ProtoSchool or proto.school, but there's no reason in her mind not to use PL. 

A new footer seems like an appropriate place to include this, but if we delay the implementation of a more extravagant footer, we should add this attribution sooner.

**Comment by zebateira** [comment]
### Notes on implementation

- Create a new `src/components/Footer.vue` component.
- Include it in all the `src/pages` page components, after the `section` element

**Comment by zebateira** [comment]
### Footer Content

(Logo) ProtoSchool
Interactive tutorials on decentralized web protocols

Tutorials:

- IPFS
- Filecoin
- Multiformats

Events:

- Upcoming Events
- Register ProtoSchool Workshop
- Past Events

Contribute:

- Build a tutorial
- Host an event
- Share feedback (link to profiling user survey?)

Community:

 - Github
 - Twitter
 - Newsletter (link to `/news` or mailchimp page)

Related Projects:

- IPFS
- Filecoin
- libp2p
- Multiformats

This is inspired by Eric's proposal for the new IA.
Also note that all of this information will most likely not fit into a single row, so it might need to wrap into 2 rows.
