### ISSUE TITLE
Bug: Failed forwarding of chapters to events page

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#516]
Forwarding from /chapters to /events is failing on Netlify: 

![image](https://user-images.githubusercontent.com/19171465/89456952-9e284f80-d732-11ea-9308-123d88663ea6.png)

**Comment by terichadbourne** [comment]
The forwarding works for /#/chapters, just not for /chapters. And is it intentional that chapters is in our sitemap?

**Comment by zebateira** [comment]
#518 addresses this. Can you check @terichadbourne ?
