### ISSUE TITLE
Bug: Failed metadata rendering on all but homepage and specific tutorial pages

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#517]
After merging #505 I ran all of the URLs from the sitemap through metatags.io. I got the expected results for the individual tutorial landing pages and the homepage. All of the other pages had the wrong title (ProtoSchool | ProtoSchool) and show the card image but no description: 

events
host
build
contribute
news
tutorials

Here's an example for events: 

The metadata in the inspector shows right description, title, and og:title: 

![image](https://user-images.githubusercontent.com/19171465/89457848-0c214680-d734-11ea-8dff-69da3b0ece46.png)

metatags.io: 

![image](https://user-images.githubusercontent.com/19171465/89457979-4559b680-d734-11ea-9600-7c013b99f31c.png)

Twitter card validator: 
![image](https://user-images.githubusercontent.com/19171465/89457935-2f4bf600-d734-11ea-9c0a-76c0914a9453.png)

Facebook debugger without a trailing slash:
![image](https://user-images.githubusercontent.com/19171465/89458119-818d1700-d734-11ea-9922-2d0b6fe8782e.png)

Facebook debugger with a trailing slash: 
![image](https://user-images.githubusercontent.com/19171465/89458260-be590e00-d734-11ea-868f-488d8a061aa6.png)

The Facebook scraper can't see the descriptions I see in the Chrome inspector, even when it doesn't have the chapters v events problems. For example, it sees this for tutorials and then invents its own description from the page content: 

https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fproto.school%2Ftutorials%2F

**Comment by terichadbourne** [comment]
Not clear whether this is fully related but it may matter which version of trailing slash or no trailing slash we use in the sitemap: https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html

**Comment by zebateira** [comment]
#519 should address this. can you check @terichadbourne ?
