### ISSUE TITLE
SEO: Lesson URLs - deal with users landing directly into a lesson page

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#523]
From the convo in #506, I'm creating this issue to track the new UI change so we can redirect users to the beginning of the tutorial, if they prefer to do so.

Todo:

 - [x] Add lessons URLs to sitemap
 - [x] Add UI Callout to send users to the first tutorial lesson

**Comment by terichadbourne** [comment]
Some additional context: 

Specific lessons are now popping up in search results, but it has the same description for each (currently matching the tutorial description) and presumably is also using the content of the lessons themselves in addition to the description to decide, for example, to surface these 2 of 7 lessons: 

![image](https://user-images.githubusercontent.com/19171465/90427556-b3856e00-e090-11ea-9899-1b017e3bdeb7.png)

I'm curious if there's anything we should do in the lesson descriptions themselves to encourage people to start from the beginning, or if we should use all our space there to take advantage of relevant keyword. (Suggestions, @andrew?) We could also use the priorities to emphasize number 1 in case multiple pop up from the same search results, I suppose.

**Comment by andrew** [comment]
@terichadbourne I'd let google run those for a while, they track the individual click through rates of each lesson, might end up pushing lesson 1 more often if it gets better click throughs. Also there's no harm in having multiple results for a given search. 

One other thing to remember is that what you see in a google search result may not be the same as everyone else, here's what I get in the UK:
![Screenshot 2020-08-18 at 09 35 04](https://user-images.githubusercontent.com/1060/90490106-1c72f180-e136-11ea-8f3c-deaa8e66ba96.png)
