### ISSUE TITLE
Chore: Move hosting to Fleek

### ISSUE THREAD

**Issue by zebateira** [ProtoSchool/protoschool.github.io#524]
Testing deployment on Fleek seems to be working now. This is the final checklist for deploying production to Fleek:

- [x] Update fleek configuration with the new config:
  - Build command: `npm run build:fleek`
  - Publish directory: `dist`
  - docker image name: `fleek/puppeteer`
- [x ] Add CDN redirects (ask fleek support team)
  - `/chapters -> /events` (handling client side, works for users but not good for SEO)
  - `* -> /404` (handling through ipfs-4040.html file) 
- [x] Update custom domain in Fleek

This will probably be done when I'm back, in the first week of September.

/cc @terichadbourne @andyschwab

**Comment by andyschwab** [comment]
Up and running at: https://protoschool.on.fleek.co/

**Comment by andyschwab** [comment]
This deployment builds from `main`, and will generate preview builds for all PRs.

**Comment by zebateira** [comment]
This is looking great.
@terichadbourne I've noticed one thing: The events list is not complete by not showing virtual events (_I think_).

**Comment by zebateira** [comment]
> @terichadbourne I've noticed one thing: The events list is not complete by not showing virtual events (I think).

So this was because the build script was not running correctly. This is not fixed.

**Comment by terichadbourne** [comment]
We've moved to Fleek with DNSlink disabled. Thanks for all the work on this, @zebateira & @andyschwab. 🎉

We hope to enable DNSlink next quarter. For remaining challenges / blockers to making that happen (and making ProtoSchool discoverable on IPFS Companion) please see issue #548.
