### ISSUE TITLE
List specific projects / implementations / APIs

### ISSUE THREAD

**Issue by xxhatemxx** [ProtoSchool/protoschool.github.io#531]
Have an idea for a new tutorial? We'd love to discuss it. Please share some info
to get the discussion started.

**What networking protocol would this tutorial address?**
List specific projects such as IPFS, IPLD, libp2p, Multiformats, etc.

**What will the user know how to do after completing this tutorial?**
Be specific, eg "Upload files using the JS IPFS file API"

**Describe the content of the tutorial.**
Describe the tutorial in more detail. Do you have ideas for the APIs or methods
to be taught, format to be used, or real-world examples to be included?

**What potential challenges do you forsee in building this tutorial?**
For example, does the format you have in mind not fit the current capabilities
of the site?

**Additional context (optional)**
Would this ProtoSchool tutorial fit into a broader initiative to reach a certain
user or use case? Did you get the idea because of a gap you saw while exploring
a current tutorial?

**Would you like to build this tutorial yourself?**
Do you have the time and skills to build this tutorial yourself, after some group
brainstorming, or do you hope that someone else might have the bandwidth to do so?

**Comment by terichadbourne** [comment]
Hi @xxhatemxx! Looks like you may have used the wrong issue template and aren't actually proposing a new tutorial. Can you tell me more about where you'd like to see more specifics about networking protocols or specific API implementations? Maybe share screenshots of where you wish you'd seen more detail?
