### ISSUE TITLE
Bug: Incorrect tab labels when browsing internally

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#540]
Thanks to @ericronne for reporting this one!

When you click around the pages of our site using our nav bar in Chrome, the titles on the Chrome tabs are frequently incorrect: 

![image](https://user-images.githubusercontent.com/19171465/92008670-74ece600-ed15-11ea-9985-bd334a7a9916.png)

Playing around with this myself, it appears that it's often the case that when you change tabs within ProtoSchool via the nav, the title on the Chrome tab changes to the title of page you were previously on. (However, this is definitely not always true, and it might be that it stops being true when you revisit a previously visited page.) You always have to click away from the Home tab at least twice to get to a custom (but incorrect) title that's different. And you seem to always get the correct title when clicking on Home. 

I've double-checked that the metadata for static pages is set correctly in [src/utils/head/data/static-pages.js](https://github.com/ProtoSchool/protoschool.github.io/blob/main/src/utils/head/data/static-pages.js), and I get the correct titles in Chrome tabs when I visit a page directly from a URL rather than via internal navigation, regardless of whether I've visited that page before.  The distinction in behavior based on navigation method leads me to believe something's not firing at the correct time on internal nav. Likely the timing issue sits in  [src/utils/head/index.js](https://github.com/ProtoSchool/protoschool.github.io/blob/main/src/utils/head/index.js) or [src/utils/head/data/route.js](https://github.com/ProtoSchool/protoschool.github.io/blob/main/src/utils/head/data/root.js). Maybe `window.location.pathname` doesn't have time to change before it's read and used to set the metadata?  

Since it's only happening with internal nav, I assume it's not creating messed up social cards, but we should double check. 

The behavior I've described above is the same for me in Chrome, Safari, and Firefox.

@zebateira let's explore this one together when we meet tomorrow.

**Comment by zebateira** [comment]
closed in #547
