### ISSUE TITLE
Boost entry points to ProtoSchool (Q3 2020 OKR)

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#544]
Most of our efforts to boost entry points to ProtoSchool are scattered across repos of other projects, but collecting some of the many completed tasks here. (Will open a second open-ended issue for linking suggestions that haven't yet been addressed.)

In Q3 2020, we: 
- Claimed the "Tutorials" button on js.ipfs.io for ProtoSchool
- Added ProtoSchool to the footer of the new Filecoin website
- Worked with IPFS newsletter signups to direct traffic to each other and adding tracking so we can see how many folks we're driving to those signup pages
- Gave all relevant project teams access to custom URLs that direct to filtered tutorial lists ("courses") covering their project on ProtoSchool
- Added ProtoSchool links to relevant spots in Filecoin and IPFS docs
- Got increased social coverage from the Filecoin team around the launch of our first Filecoin tutorial

@zebateira What am I forgetting here?

**Comment by zebateira** [comment]
Looks good to me 👍
