### ISSUE TITLE
Separate Mailchimp build from specific user’s permission level 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#554]
The Mailchimp build that pulls new workshop submitters into our mailing list recently failed because we had reduced the permissions of the user who originally set it up. Restoring the admin status of that user fixed the problem, but we should find a way to tie the build to the primary account instead of a user account moving forward.

**Comment by zebateira** [comment]
So apparently, this is not possible: https://mailchimp.com/help/about-api-keys/

So we solved this by changing the ownership of the API key from my account to @terichadbourne's.
API Key updated in fleek build settings and the vault in the password manager.
