### ISSUE TITLE
Update Anatomy of a CID screenshots to match new CID Inspector formatting

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#563]
Once @lidel merges his improvements to the CID Inspector ([see PR](https://github.com/multiformats/cid-utils-website/pull/35)), we'll need to update the images in [Lesson 6 of Anatomy of a CID](https://proto.school/anatomy-of-a-cid/06), which uses and describes screenshots from the inspector. 

@lidel just confirming that the changes are essentially all about formatting and that there haven't been actual changes to how CIDs work that need to be addressed either there or elsewhere in that tutorial?

**Comment by lidel** [comment]
@terichadbourne yes, changes are only visual, no change to the way CIDs work.

ps. I merged it, changes are live at https://cid.ipfs.io
