### ISSUE TITLE
Lesson Feedback%3A Verifying Storage on Filecoin - Lesson 2 (Preparing and transferring data)

### ISSUE THREAD

**Issue by Humairah28** [ProtoSchool/protoschool.github.io#569]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**

**What's confusing about this lesson?**

**What additional context could we provide to help you succeed?**

**What other feedback would you like to share about ProtoSchool?**

**Comment by terichadbourne** [comment]
Hi, @Humairah28! Look forward to learning more about the question you have about lesson 2 in Verifying Storage on Filecoin. Could you please answer these questions for us when you have a moment?

**Comment by terichadbourne** [comment]
URL of the lesson that's confusing:

What's confusing about this lesson?

What additional context could we provide to help you succeed?

What other feedback would you like to share about ProtoSchool?
