### ISSUE TITLE
Bug: IPFS not installing when repo is cloned and installed

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#576]
In testing, multiple non-coder users have been unable install our dependencies after cloning the repo for the first time, with errors showing that it's IPFS that isn't installing properly. Both had Macs and had installed NPM from its website. 

@zebateira is working on debugging.

**Comment by mitchwagner** [comment]
OS: macOS Catalina 10.15.7
node.js: 15.3.0 (installed via nvm)
npm: 7.0.14

I was able to run the wizard a few weeks ago. After a fresh pull of the repository, I received an error saying the "inquirer" could not be found. After installing it (npm install inquirer), I was again able to run protowizard.

I'm not entirely sure the errors are related, but at least here's a datapoint indicating a working config.
