### ISSUE TITLE
Lesson Feedback%3A Data Structures - Lesson 3 (The decentralized web: Content addressing)

### ISSUE THREAD

**Issue by pheonixcornell61** [ProtoSchool/protoschool.github.io#583]
I  am confused about  Centralized internet vs. Tor (Dark web browser)

What is the difference between Tor and a centralized web

Tor allows you to search without being watched by third parties who collect your personal info and preferences. Tor Browser claims to be undetectable from hackers, but I think it's just as hackable. So how is a centralized internet going to be better with information readily available for anyone? It would be a good thing for the public to have access to real uncensored global news, but people have been frauded far to many times already. How would this centralized internet be publicly acceptable? Who is going to teach the public to code or cryptograph info for sharing, let alone  for firewall protection?

**Comment by terichadbourne** [comment]
Hi @pheonixcornell61. It sounds like you may be confusing the decentralized web with the dark web. ProtoSchool's content is all about the decentralized web, where content addressing provides trust among peers who host each other's data, without relying on centralized servers as HTTP does. 

I don't have experience with Tor or the dark web, and we don't cover those topics on ProtoSchool, so I'd encourage you to visit [Tor's website](https://www.torproject.org/) to learn more. Based on their FAQs, I believe Tor is a tool/browser for protecting your identity while you visit websites, including both those hosted on the centralized web and some sites that aren't found by traditional search engines.
