### ISSUE TITLE
Update emoji in Merkle DAG tutorial diagrams

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#592]
Fix diagrams in Merkle DAGs tutorial so emoji aren't reused. For more see comments in #582: https://github.com/ProtoSchool/protoschool.github.io/pull/582#issuecomment-759860966

@mitchwagner I believe you're on top of this, but let me know if you need someone else to step in. Thanks!

**Comment by mitchwagner** [comment]
Yep, I'm on it.

**Comment by mitchwagner** [comment]
... still on it :) Sorry, life got unexpectedly busy for a while, there. I'll have a PR in for this by the end of the week(end).
