### ISSUE TITLE
Filecoin logo not rendering on news page

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#602]
![image](https://user-images.githubusercontent.com/19171465/105754082-a1e5a380-5f17-11eb-8160-135488fd162b.png)

**Comment by terichadbourne** [comment]
I'm not able to figure out what's going wrong with the Filecoin logo on the News page. 

![image](https://user-images.githubusercontent.com/19171465/105756075-25a08f80-5f1a-11eb-8062-b6d00944ee06.png)

There's a filecoin logo in the right location and it's displaying in other parts of our code. 

![image](https://user-images.githubusercontent.com/19171465/105756140-394bf600-5f1a-11eb-801f-5f4ec192d27d.png)

In the inspector the image source gets changes to have extra digits in the middle of it: 
![image](https://user-images.githubusercontent.com/19171465/105755698-a90db100-5f19-11eb-83e8-416b068e01e5.png)


![image](https://user-images.githubusercontent.com/19171465/105755563-75328b80-5f19-11eb-9409-f34fef62a6fc.png)

But this happens to the IPFS image as well which shows up just fine: 
![image](https://user-images.githubusercontent.com/19171465/105755871-e2462100-5f19-11eb-9851-e3374888a200.png)

![image](https://user-images.githubusercontent.com/19171465/105755953-fbe76880-5f19-11eb-8173-ca92d877ebb2.png)

@zebateira Any ideas?

**Comment by zebateira** [comment]
@terichadbourne fixed! I missed this one icon in the projects newsletter when adding the `ProjectIcon` component to the code base.
