### ISSUE TITLE
Lesson Feedback%3A Mutable File System - Lesson 1 (Introducing IPFS)

### ISSUE THREAD

**Issue by adrapper** [ProtoSchool/protoschool.github.io#604]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**

https://proto.school/mutable-file-system/02

**What's confusing about this lesson?**

It appears that everything... well almost everything connected with IPFS is terminal-based and needs a good degree of coding skills. 

Why is that? 

Many of use want to produce content not code, i.e. protect our web content by creating a decentralised website, not leant about the technical back end.

I used to code websites in HTML and CSS back in the day but use WordPress now. As someone who works more like a journalist, I am looking to produce and protect information. 

Where should I be looking or what should I be learning. 

Am I too early to the IPFS and the decentralised web?

**What additional context could we provide to help you succeed?**

On the old web... I register a DOMAIN and that is where people can find me. How does this work in the decentralised web? 

There appear to be people who register... I can not remember yet the term, but static IPFS starting points, but that appears to be relying on the old system of centralised points of vulnerability. 

**What other feedback would you like to share about ProtoSchool?**

**Comment by autonome** [comment]
Hey @adrapper! Thanks for sharing this. A few thoughts...

The old web has been in development for over 30 years. The cow paths are well trodden. The model is clear. The tools are slick. The workflows are proven out. The new web? Not so much. The primitives are getting clearer, the libraries and patterns are pretty good, but we're definitely still in the early days of tooling and workflow, I think. Protoschool teaches the primitives and data structures.

That said... there are some things emerging:

* [Textile](textile.io/), [OrbitDB](https://orbitdb.org/), [Fission](https://fission.codes/) and [3Box](https://3box.io/) are examples of libraries and frameworks that translate web3 into more traditional concepts for web2 developers.
* [Fleek](https://fleek.co/), [Pinata](pinata.cloud/) and [Infura](https://infura.io/) are services for hosting IPFS data and applications in both web2 and web3 ways.
* [Unstoppable Domains](unstoppabledomains.com/) and [ENS](https://ens.domains) are services for using web2 DNS name resolution approaches to access web3 content and services.

**Comment by autonome** [comment]
Oh, and Textile released a Wordpress plugin to easily put WP content on IPFS: https://wordpress.org/plugins/textile-tools/

And Unstoppable Domains has guide for doing this too: https://community.unstoppabledomains.com/t/convert-wordpress-site-for-use-with-ipfs-guide/327

**Comment by adrapper** [comment]
Wow, so good to actually find someone to talk to about this. 

All the trainings I can find are… very… terminals. But I have IPFS Desktop running on my Mac and it appears to put files I drop into this state into the… Hummm do we need a new name for the cloud? The decentralised web.

Should I not be able to build a website in a folder that is imported into IPFS Desktop, and proof my site in in the decentralised web?

How you make that findable is another matter. 

Unstoppable Domains and ENS look like it is taking the decentralised web and making it centralised again. Or am I misunderstanding that?

Sorry to be such a new-be at this. 

I will look through the resources that you have included and try to get a handle on this. 

I would more than happily dive into the terminal and all, but… that makes or would make IPFS for the few and not the many. 

Andrew

**Comment by autonome** [comment]
> I have IPFS Desktop running on my Mac and it appears to put files I drop into this state into the… Hummm do we need a new name for the cloud?

Any files you add via the IPFS desktop web UI are first added to the local IPFS repository (like a local database) and then your IPFS node will respond to requests for the addresses of those files.

> Should I not be able to build a website in a folder that is imported into IPFS Desktop, and proof my site in in the decentralised web?

You can drag and drop a folder or multiple files into the web UI, and then get the CID address and view through the IPFS gateway. There's a menu item in IPFS Desktop to get that URL.

Fleek allows you to do this - can pull from a Github repo, etc. There are several command line tools as well which ease this also.

> Unstoppable Domains and ENS look like it is taking the decentralised web and making it centralised again. Or am I misunderstanding that?

They both offer ways to configure mappings of readable names to IPFS addresses that are accessible through regular DNS. Yes, there is some centralization in how these work today. That won't always be the case, and these are just early movers in space that I expect will see interoperability and standardization over time.

> I would more than happily dive into the terminal and all, but… that makes or would make IPFS for the few and not the many.

Gotta start somewhere. Due to the hard work of the services and tools I listed above, it's 10,000 times easier than last year, the year before, the year before that...

**Comment by adrapper** [comment]
Thank you so much. 

By the way, is there a better place for me to ask these questions?

What is the best… Podcast or news letter or… to be kept up-to-date on IPFS?

One of the main points of IPFS appears to be the making of information permanent and to stop the loss of information from the web. Or to say help students maintain control of their course work. It may be that I do not understand something or that we are just very early in this protocol, but changing a file name from "snow on a christmas tree.jpg” to “QmcdbXjDKuhh1jTy8HoqvbLpDFXmiJngKJecBkscjphwTT” may immutably preserve the data, but does it not very quickly make it unfindable unless I maintain a database of the cross reference of content to its hash?

Do tell me if I should be asking this somewhere else.

**Comment by autonome** [comment]
> By the way, is there a better place for me to ask these questions?

Yes! The forums are super active, and a great place to ask: https://discuss.ipfs.io

> What is the best… Podcast or news letter or… to be kept up-to-date on IPFS?

We have a weekly newsletter! Subscribe link at the bottom here: https://ipfs.io/

> One of the main points of IPFS appears to be the making of information permanent and to stop the loss of information from the web. Or to say help students maintain control of their course work. It may be that I do not understand something or that we are just very early in this protocol, but changing a file name from "snow on a christmas tree.jpg” to “QmcdbXjDKuhh1jTy8HoqvbLpDFXmiJngKJecBkscjphwTT” may immutably preserve the data, but does it not very quickly make it unfindable unless I maintain a database of the cross reference of content to its hash?

Readable names, file metadata, search indices, dynamic content - yes lots to build on top of these primitives. There are lots of projects around which address these gaps, but the landscape hasn't settled yet.

**Comment by adrapper** [comment]
Thanks so much. 

Will move over to the forum for future needs.

**Comment by terichadbourne** [comment]
Thanks so much for sharing these questions, @adrapper! Onboarding is a big challenge for many dweb projects, and we're excited to keep creating content that can help both coders and non-coders alike. Really appreciate your perspective and feedback!
