### ISSUE TITLE
Lesson Feedback%3A Basics - Lesson 1 (Create a node and return a Content Identifier (CID))

### ISSUE THREAD

**Issue by jinhale** [ProtoSchool/protoschool.github.io#614]
**URL of the lesson that's confusing:**

https://proto.school/basics/01/

**What's confusing about this lesson?**

The code is not editable on Chrome on my mobile device: Samsung J7.

**What additional context could we provide to help you succeed?**

I could only write `returnawait` and refreshing didn't help after that. Refreshing didn't erase the text. 

**What other feedback would you like to share about ProtoSchool?**

Overall it's a great experience.

**Comment by terichadbourne** [comment]
So sorry about that, @jinhale, and thank you for sharing your experience. Our non-coding tutorials should work well on mobile, but the code editor doesn't provide a good experience there. We're planning to add an indicator to let folks know that we recommend tackling coding challenges from a laptop.

Closing this issue in favor of #147.
