### ISSUE TITLE
Add recent tutorials to event hosting form 

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#625]
- [x] Add recent tutorials to form for event hosts where they select event content
- [x] Add this step to our proposed documentation for what to do when a tutorial is published

**Comment by terichadbourne** [comment]
@zebateira Could you please just double-check that this screenshot below looks accurate? If so we can close this. Thanks!

![image](https://user-images.githubusercontent.com/19171465/110700392-e4a8c580-81bd-11eb-9e7f-5013770a4c63.png)

**Comment by zebateira** [comment]
Perfect 👌 💯
