### ISSUE TITLE
Lesson Feedback%3A Regular Files API - Lesson 3 (Add a file)

### ISSUE THREAD

**Issue by jasonwalks** [ProtoSchool/protoschool.github.io#630]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**

**What's confusing about this lesson?**

**What additional context could we provide to help you succeed?**

**What other feedback would you like to share about ProtoSchool?**

A possible typo：When you add a file to IPFS, you're putting it only in your own node, "but" making it accessible by peers on the network.  Should be "not" eh?

**Comment by terichadbourne** [comment]
Thanks for flagging, @jasonwalks! I think I disagree with your interpretation here... you ARE making it accessible (discoverable) to others when you add to your own node, you're just not magically making it transfer to their computers. But I agree this sentence could be more clear! 

I've opened PR #633 with a proposed solution. Would this help to clarify? https://github.com/ProtoSchool/protoschool.github.io/pull/633/files

**Comment by jasonwalks** [comment]
Oh I see your point. Yep, my bad for not reading it carefully. And yep, the revision is good.

**Comment by terichadbourne** [comment]
Thanks for reviewing, and glad this edit is helpful!
