### ISSUE TITLE
Lesson Feedback%3A Content Addressing - Lesson 1 (Identifying and retrieving data on the web)

### ISSUE THREAD

**Issue by sn0n** [ProtoSchool/protoschool.github.io#668]
Have a question or suggestion regarding a specific ProtoSchool lesson? Please use this template to share it!

**URL of the lesson that's confusing:**
https://proto.school/content-addressing/01

**What's confusing about this lesson?**
Is it Lars, or Larry? 

**What additional context could we provide to help you succeed?**
I mean.... Pick one. 

**What other feedback would you like to share about ProtoSchool?**
Lars sounds cooler, but maybe Larry is the man!

**Comment by terichadbourne** [comment]
Thanks for the catch, @sn0n! 😂
