### ISSUE TITLE
[Fix] Lack Of Some Dependencies

### ISSUE THREAD

**Issue by daijiale** [ProtoSchool/protoschool.github.io#74]
lack of some dependencies in package.json ：
`npm install --save leveldown webcrypto-shim webrtcsupport`

<img width="708" alt="2018-11-01 3 19 35" src="https://user-images.githubusercontent.com/6550752/47838413-497fd400-ddea-11e8-8e15-02478d23ee54.png">

```
  "dependencies": {
    "leveldown": "^4.0.1",
    "webcrypto-shim": "^0.1.4",
    "webrtcsupport": "^2.2.0"
  },

```

I tried it out, support online debugging and studying of IPFS Tech Courses,
 Great PWA experience ，expect more courses ！

**Comment by terichadbourne** [comment]
Resolved (per @mikeal)
