### ISSUE TITLE
Feature: Support for coding visual elements in exercise.

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#75]
I was thinking about building a "file drop" tutorial but quickly realized that it requires a visual component area and we don't yet support that.

What would be the best way to create/support something like this? How do similar projects deal with this?

**Comment by mikeal** [comment]
This is **not** part of the 1.0 release :)

**Comment by terichadbourne** [comment]
Are you referring to something like a drag and drop area?

**Comment by mikeal** [comment]
@terichadbourne exactly, but really any visual programming we don't currently support.

**Comment by terichadbourne** [comment]
@mikeal Was this issue addressed when we created the file upload lesson format, or is there more you have in mind?

**Comment by mikeal** [comment]
yup, close it! :)
