### ISSUE TITLE
Feature: enable web analytics

### ISSUE THREAD

**Issue by dharmapunk82** [ProtoSchool/protoschool.github.io#770]
Hi team-

I'm helping to form up our google analytics data, and noticed that an analytics property was created for your site but no data is flowing to it. 

Please add the following code snippet to the site header to enable web analytics:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-96910779-4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-96910779-4');
</script>

**Comment by Stebalien** [comment]
We use countly, which is already enabled.

**Comment by dharmapunk82** [comment]
Thanks for confirming and sorry for slow reply-- I sent these out before doing a review of countly, closing and have updated documentation to reference countly as appropriate source of truth for analytics for this site.
