### ISSUE TITLE
Re-write IPLD lessons to new API

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#79]
The CBOR API changes have [been merged upstream](https://github.com/ipfs-shipyard/proto.school/issues/68#issuecomment-435486857) into the latest IPFS. This means we need to:

* Update the version of `js-ipfs` in the lessons.
* Update the IPLD lessons to use the new API
  * Replace `{"/": cid.toBaseEncodedString()}` with `cid`.

**Comment by terichadbourne** [comment]
@mikeal Are you game to take on fixing the lesson itself, with any instruction changes that are immediately obvious to you, and then I can go back through and proof it for comprehensibility in its new form? 

I'll reference the old issue when I do that, as there was some stuff like suggesting a while loop that's unrelated to the change in how the API works.
