### ISSUE TITLE
Lesson Feedback%3A Anatomy of a CID - Lesson 6 (One hash, multiple CID versions)

### ISSUE THREAD

**Issue by mrodriguez3313** [ProtoSchool/protoschool.github.io#801]
**What's confusing about this lesson?**

I had confusion/ question on this portion under the first screenshot on the [title page](https://proto.school/anatomy-of-a-cid/06):
> * Multihash: breakdown of the multihash into the hashing algorithm used (18 is the code for sha2-256), the length of the hash (256 bits, which equates to 32 bytes), and the content hash itself (digest hex).

Where did 18 come from if the code in the screenshot shows 12?

**Comment by ribasushi** [comment]
The screenshot shows `0x12` which ( `0x...` ) is a standard way to denote hexadecimal base. The decimal `18` is `0x12` in hex.

**Comment by mrodriguez3313** [comment]
Makes sense. idk why I didn't think about that. Thank you
