### ISSUE TITLE
Move repo to ProtoSchool org

### ISSUE THREAD

**Issue by mikeal** [ProtoSchool/protoschool.github.io#94]
We've got the ProtoSchool org setup now and we need to migrate this repo to ProtoSchool and name it "protoschool.github.io" to get gh-pages to work properly.

I'm not an org owner so I can't do this. Someone can either add me as an org owner for a few minutes to do the transfer or they can initiate it themselves.

@lgierth @daviddias @flyingzumwalt @victorb

**Comment by mikeal** [comment]
@daviddias invited :)

**Comment by daviddias** [comment]
done the transfer :)

**Comment by terichadbourne** [comment]
Thanks @daviddias! 

Looks like it was moved as still `proto.school`, so I've renamed the repo to `protoschool.github.io`. 

@mikeal Can you help me figure out these two issues? 
- https://protoschool.github.io/ is showing the README instead of loading the Vue app. Do you know what needs to be done to fix that? 
- https://proto.school/is currently broken. Do we need to fix some more settings in the new repo/org to get it live again at that address?

**Comment by terichadbourne** [comment]
@mikeal update: I figured out how to make the contents of our custom domain match https://protoschool.github.io/, so now they're both showing the readme. :)

**Comment by terichadbourne** [comment]
Might this be an issue of Travis not being properly authorized?

**Comment by terichadbourne** [comment]
@mikeal I tried rebuilding the last successful build in master, but it didn't help. I thought of switching GH to consider gh-pages the default in case Travis is serving it there, but the option is disabled. My last thought is that maybe Travis requires a new token issued from the new repo? 

I need to head out for an event, so if you have time to try that it would be awesome. Or feel free to drop some clues for other things I can try when I'm back online.

**Comment by mikeal** [comment]
The problem is that org pages require you use the `master` branch instead of the `gh-pages` branch. I'll work on a fix today.

**Comment by mikeal** [comment]
Update: the default branch is now `code` instead of `master`. We'll need to update the existing PR's to point at that branch. This was the only way to get it working again.

Travis still hasn't updated it's information about the default branch so it's missing builds. This should clear itself up by tomorrow and if it doesn't I'll try to fix it again.

**Comment by mikeal** [comment]
Update: I reconfigured all the PR's to point at the `code` branch.
