### ISSUE TITLE
Question on Lesson 07: Traverse through all posts, starting with the most recent (/blog/07)

### ISSUE THREAD

**Issue by nelsonic** [ProtoSchool/protoschool.github.io#96]
Greetings IPFSers!

I've approached the proto.school as a complete beginner to IPFS (_but a reasonably experienced JS dev_),
I felt that the final step in the Blog tutorial was a little confusing ...
I've sat with quite a few (_hundred_) beginners over the years 
and feel that _most_ would give up if faced with the `TypeError` ...

1. URL of the lesson that's confusing: https://proto.school/#/blog/07

2. What's confusing about this lesson?
It's unclear how to get the value of `prev` when traversing ...
and also unclear that attempting to get the CID for an invalid `cid` will throw a `TypeError`.

3. What additional context could we provide to help you succeed?
Not being able to `console.log` in the `traversePosts` function when there's a `TypeError` makes it difficult to debug. all I see is:
![image](https://user-images.githubusercontent.com/194400/49479358-9ce6a700-f81a-11e8-88d5-02141219588c.png)
Which is basically "**_game over_**" as far as error messages are concerned.

4. What other feedback would you like to share about ProtoSchool?

I _agree_ with @terichadbourne's re-opening of https://github.com/ipfs-shipyard/proto.school/issues/68#issuecomment-444300812 
I don't feel it's as beginner friendly as it could be. 😞 
I _eventually_ figured out how to solve the `traversePosts` by using a `while` loop (_after reading #68 ..._)
I would _love_ to see the completion stats on this workshop to know how many people "figure it out" ...

My complete journey through `proto.school` is captured in: https://github.com/nelsonic/learn-ipfs/issues/5#issuecomment-444310649

> **Context**: I'm trying to figure out if IPFS is in a "useable" state to start building apps ... 💭
And if it's possible, my intention is to write a _detailed_ tutorial for how to do that.
e.g: https://github.com/dwyl/todo-list-javascript-tutorial

**Comment by terichadbourne** [comment]
Thank you so much for your feedback, @nelsonic! I'm a total beginner with IPFS and not a JavaScript expert, so I definitely found lesson 7 pretty jarring when I first attempted it, and am still struggling a bit.  

We're in the middle of updating the ProtoSchool workshops to reflect a change in the IPFS DAG API that makes it easier to work with CID links, which in turn enables us to create simpler instructions. I've added in a few clues in the new draft about using a while loop, etc. (see PR #79). Mind if I ping you when the updates are live so I can get your take on whether the new setup (changes to both code and instructions) is clear enough?   

I really appreciate that capture of your whole journey through ProtoSchool as well!

**Comment by nelsonic** [comment]
@terichadbourne yes, I would love to be kept informed of the new `proto.school` workshop updates. 👍 
I'm very keen to figure out how to start using IPFS for real and having beginner-friendly learning materials is _essential_ for ensuring that new people viewing the code we write can _understand_ it. 

Great work so far BTW! thanks! ✨

**Comment by terichadbourne** [comment]
@nelsonic The live site now reflects a new (and simpler) API for CID links, which leads (IMHO) to clearer instructions as well. There's another new development that I find really exciting, but I'll let you discover it for yourself. :) 

If you have the time and interest, I'd love your feedback on whether Lesson 7 of the blog workshop feels more approachable now with the new instructions and whether there's still stuff there that's tripping you up. I'd be curious to see what your first instincts are for the solution code, whether they work or not, given the new instructions.

**Comment by nelsonic** [comment]
@terichadbourne taking a look now ... ⏳ (_thanks for keeping me informed_)

**Comment by nelsonic** [comment]
Second time round: https://github.com/nelsonic/learn-ipfs/issues/5#issuecomment-445864393
I feel that the linking between content is _much_ more intuitive. Was able to traverse the tree with _ease_.
Don't know if a beginner would think to use a **`while`** loop. 🤔 
But everything works and the exercise is _much_ easier to follow, so happy to close this issue.  👍
